---
title: Evaluación multitemporal de la resiliencia comunitaria ante desastres por riesgo tecnológico en la comuna 10 del municipio de Dosquebradas
author:
- name: Evelin Langebeck Cuéllar
  affiliations:
  - Unidad Nacional para la Gestión del Riesgo de Desastres, Bogotá, Colombia
- name: Nicolás Giraldo Hernández
  affiliations:
  - Dirección de Gestión del Riesgo de Desastres -- Alcaldía de Dosquebradas, Dosquebradas, Colombia
keywords:
- Resiliencia comunitaria ante desastres
- riesgo tecnológico
- herramienta ARC-D
- gestión del riesgo de desastres
- análisis multitemporal de resiliencia
- percepción del riesgo
abstract: '[[evelin.langebeck@gmail.com]{.underline}](mailto:evelin.langebeck@gmail.com)'
categories:
- Sesión 13. Iniciativas para comunidades resilientes
---

[[evelin.langebeck@gmail.com]{.underline}](mailto:evelin.langebeck@gmail.com)

La percepción de los eventos tecnológicos de las comunidades es parte fundamental de la comprensión de la gestión del riesgo de desastres. En 2011 en el municipio de Dosquebradas (barrio Villa Carola) se presentó un evento Natech, que ocasionó 33 pérdidas humanas, así como físicas y materiales, desbordando las capacidades de respuesta institucionales y comunitarias. En este capítulo se describe la aplicación de la herramienta ARC-D para medir y evaluar la resiliencia comunitaria multitemporal ante desastres. Se aplicó una metodología con enfoque cualitativo para la interacción comunidad-territorio y una de enfoque cuantitativo para el procesamiento de datos. Para la discusión comunitaria se empleó un instrumento tipo encuesta medida por grupo focal con facilitador, en la que se evaluaron cuatro áreas temáticas. La aplicación de la herramienta tuvo un diagnóstico de resiliencia previo y una prueba piloto de ajuste al grupo focal. Se encontró un nivel bajo de resiliencia en el pre-evento (año 2011) con un mayor énfasis en la baja comprensión del riesgo, contrario al componente más alto que corresponde a cohesión social en el territorio. El post-evento (año 2021) obtuvo un nivel de mediana resiliencia con mejores resultados en el fortalecimiento de la gobernanza para gestionar el riesgo de desastres, reflejado en su componente destacado que fue la participación de las mujeres. Se concluye que la comuna 10 de Dosquebradas mejoró sus capacidades de resiliencia comunitaria ante desastres por riesgo tecnológico de 30,08% a 60,18%, destacando el aumento de la participación comunitaria, la organización social y la apropiación de la cultura de la prevención del riesgo. Se recomienda a los entes territoriales y locales conocer la percepción del riesgo de las comunidades para enfocar adecuadamente sus políticas, estrategias e instrumentos en la toma de decisiones.
