---
title: 'Caracterización de Amenazas de Inundación como soporte al ordenamiento territorial: Caso de estudio centros poblados Región Mojana Colombia'
author:
- name: Nelsy Verdugo R
  affiliations:
  - Profesional Especializada Grupo de Modelación y Pronósticos Hidrológicos IDEAM, Bogotá Colombia
- name: Fabio Andrés Bernal
  affiliations:
  - Subdirector de Hidrología IDEAM, Bogotá Colombia
keywords:
- Amenaza de inundación
- Modelación hidrológica
- Modelación hidráulica
abstract: '[<nverdugo@ideam.gov.co>; <fbernal@ideam.gov.co>]{.underline}'
categories:
- Sesión 11. Inundaciones, erosión fluvial y costera
---

[<nverdugo@ideam.gov.co>; <fbernal@ideam.gov.co>]{.underline}

El proceso que permite caracterizar las amenazas de inundación que se presentan en un espacio geográfico, involucra el reconocimiento de la dinámica hídrica del sistema natural en un contexto socio-económico específico. Es importante reconocer los patrones de flujo a través de un análisis de los registros históricos de las variables hidroclimáticas e identificar las alteraciones que se han presentado en el régimen como consecuencia de los procesos de uso y ocupación predominantes en las cuencas de drenaje correspondientes. Las herramientas de modelación matemática de procesos hidrológicos se constituyen en un aliado estratégico que permite analizar el amplio y variado espectro de las respuestas hidrológicas en unas condiciones de frontera que están determinadas por el comportamiento de los aportes hídricos. Estos pueden ser estimados con base en registros hidrológicos o estimados para aquellas cuencas no instrumentadas con transformaciones lluvia-escorrentía que deben ser evaluadas para garantizar su representatividad. En este caso de estudio, con alta complejidad por el intrincado sistema de caños y ciénagas que interactúan a lo largo de un año hidrológico, se analizan las estrategias de modelación hidrológica e hidráulica que permiten caracterizar la amenaza de inundación en inmediaciones de los centros poblados que conforman el núcleo mojana. Como resultado se cuenta con categorizaciones de amenaza de inundación a partir del cálculo de profundidades de lámina de agua y velocidad de flujo. Se presentan escenarios de amenaza de inundación para los principales centros poblados de la región Mojana.
