---
title: 'Los beneficios y desafíos de la investigación y la colaboración transnacionales: estudios de caso desde el campo'
author:
- name: Hamilton Bean
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
- name: Ana Maria Cruz
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
- name: Kensuke Takenouchi
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
- name: Genta Nakano
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
- name: James D. Goltz
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
- name: Subho Samaddar
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
- name: Dimitrios Tzioutzios
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
- name: Lina Maria Parra
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
- name: Hyejeong Park
  affiliations:
  - Profesor, Universidad de Colorado en Denver, hamilton.bean@ucdenver.edu(mailto:hamilton.bean@ucdenver.edu),  Profesora, Universidad de Kioto, Kagawa University,  Kyoto University,  Guest Scholar and
    Fellow, Disaster Prevention Research Institute, Kyoto University; Researcher in Residence, University of Colorado, Boulder, Norwegian University of Science and Technology,  Tohoku University
keywords:
- Investigación transnacional
- armonización internacional
- normas culturales
abstract: '**Sobre la sesión**: La \"cultura nacional\" se refiere a las actitudes, valores y creencias compartidas que caracterizan a los ciudadanos de un país. La cultura nacional influye en cómo las
  comunidades comprenden, se preparan, responden y se recuperan de los desastres. La percepción del riesgo, las prácticas de preparación, los protocolos de respuesta y las prioridades de recuperación pueden
  influirse por la cultura nacional. Por ejemplo, las diferentes normas culturales y orientaciones políticas surgieron como factores clave que obstaculizaron la armonización internacional de las prácticas
  de alerta pública móvil entre Japón y Estados Unidos. Si bien muchos investigadores del riesgo de desastres trabajan dentro de su propia cultura nacional, muchos también trabajan con culturas transnacionales.
  Los investigadores transnacionales a menudo consideran las diferencias lingüísticas, las normas culturales y otros factores que los investigadores que trabajan estrictamente dentro de su propio contexto
  cultural nacional no tienen en cuenta. La sensibilidad, la comprensión y la confianza cultural pueden desempeñar un papel fundamental en el éxito o el fracaso de los proyectos de investigación transnacionales.
  Comprender la dinámica de la investigación y la colaboración transnacionales es esencial para el desarrollo de una gestión eficaz del riesgo de desastres a nivel mundial. La sesión contó con 7 presentaciones
  que abarcaron diversos casos.'
categories:
- Sesiones Especiales
---

**Sobre la sesión**: La \"cultura nacional\" se refiere a las actitudes, valores y creencias compartidas que caracterizan a los ciudadanos de un país. La cultura nacional influye en cómo las comunidades comprenden, se preparan, responden y se recuperan de los desastres. La percepción del riesgo, las prácticas de preparación, los protocolos de respuesta y las prioridades de recuperación pueden influirse por la cultura nacional. Por ejemplo, las diferentes normas culturales y orientaciones políticas surgieron como factores clave que obstaculizaron la armonización internacional de las prácticas de alerta pública móvil entre Japón y Estados Unidos. Si bien muchos investigadores del riesgo de desastres trabajan dentro de su propia cultura nacional, muchos también trabajan con culturas transnacionales. Los investigadores transnacionales a menudo consideran las diferencias lingüísticas, las normas culturales y otros factores que los investigadores que trabajan estrictamente dentro de su propio contexto cultural nacional no tienen en cuenta. La sensibilidad, la comprensión y la confianza cultural pueden desempeñar un papel fundamental en el éxito o el fracaso de los proyectos de investigación transnacionales. Comprender la dinámica de la investigación y la colaboración transnacionales es esencial para el desarrollo de una gestión eficaz del riesgo de desastres a nivel mundial. La sesión contó con 7 presentaciones que abarcaron diversos casos.

**Objetivos**: Participar reflexivamente en las siguientes preguntas: 1) La investigación en gestión del riesgo de desastres evoca el trabajo a nivel local dentro de una cultura o sistema político nacional. ¿Cuáles son los riesgos y las recompensas de realizar investigaciones similares a nivel transnacional?; 2) Al realizar investigaciones transnacionales sobre gestión del riesgo de desastres, ¿cómo podemos interactuar de forma respetuosa y eficaz con comunidades muy diferentes a la nuestra?; 3) ¿Cómo persuadimos a los actores internacionales a participar en la investigación cuando la recompensa por su tiempo y atención es incierta, lejana o potencialmente minúscula?; 4) ¿Qué oportunidades ofrecen la traducción automática y la IA generativa a los investigadores y comunidades en gestión del riesgo de desastres que trabajan a nivel transnacional?; 5) ¿Cómo deberían los investigadores que trabajan a nivel transnacional configurar la \"experiencia\" y el \"conocimiento local\" de las ciencias sociales al servicio de objetivos compartidos más amplios?

**Justificación**: Las actitudes, valores y creencias culturales exhiben tanto estabilidad como cambio. Los investigadores que realizan proyectos transnacionales se encuentran en una posición privilegiada para observar cómo las normas culturales fomentan redes locales sólidas que facilitan la movilización durante las emergencias. Estas redes no solo mejoran las respuestas inmediatas, sino que también apoyan los esfuerzos de recuperación (incluida la preparación para el próximo desastre), que son fundamentales para la resiliencia a largo plazo. Es importante no solidificar la cultura ni reducirla a estereotipos nacionales. Sin embargo, es más probable que una comunidad adopte políticas y prácticas alineadas con las expectativas culturales. ¿Cómo pueden los académicos y profesionales de la gestión del riesgo de desastres abordar estos complejos problemas? Es probable que los estudios de caso de campo de los presentadores cuestionen algunas suposiciones sobre la cultura nacional, al tiempo que confirman otras. En última instancia, sin embargo, la integración de más investigaciones transnacionales en la gestión del riesgo de desastres podría ayudar a construir comunidades resilientes que estén mejor equipadas para manejar los desastres.
