---
title: 'Gobernanza colaborativa para gestionar los peligros del aumento del nivel del mar: un estudio de caso de turismo del País Vasco en España'
author:
- name: Giuseppe Aliperti
  affiliations:
  - Universidad de Deusto, Bilbao -- Donostia/San Sebastián, España
  corresponding: true
  email: giuseppe.aliperti@deusto.es
- name: Aurkene Alzua Sorzabal
  affiliations:
  - Universidad de Kioto, Kioto, Japón
- name: Ana María Cruz
  affiliations:
  - Universidad de Deusto, Bilbao -- Donostia/San Sebastián, España
keywords:
- Información sobre riesgos; Gobernanza colaborativa; Cambio climático; Aumento del nivel del mar; Destino turístico
abstract: Este estudio en curso examina la dinámica de adaptación de los destinos turísticos costeros, específicamente la costa vasca en España, en respuesta a la creciente exposición a las amenazas del
  aumento del nivel del mar (SLR). Utilizando el enfoque de modelos mentales, la investigación compara las perspectivas de expertos y no expertos sobre el proceso de adaptación al SLR. Se identificaron
  cuatro temas principales relacionados con las amenazas del SLR a través de una revisión de la literatura, y el estudio ofrece recomendaciones para gestionar estos problemas.
categories:
- Sesión 4. Percepción del riesgo, comportamiento humano y cultura
---

Este estudio en curso examina la dinámica de adaptación de los destinos turísticos costeros, específicamente la costa vasca en España, en respuesta a la creciente exposición a las amenazas del aumento del nivel del mar (SLR). Utilizando el enfoque de modelos mentales, la investigación compara las perspectivas de expertos y no expertos sobre el proceso de adaptación al SLR. Se identificaron cuatro temas principales relacionados con las amenazas del SLR a través de una revisión de la literatura, y el estudio ofrece recomendaciones para gestionar estos problemas.

Los hallazgos preliminares sugieren que las medidas de adaptación desarrolladas para áreas expuestas al SLR a largo plazo se pueden aplicar a los destinos turísticos costeros que enfrentan esta amenaza recientemente. La clave para una adaptación exitosa es la participación activa de las partes interesadas, en particular las empresas turísticas. Para lograrlo, la inversión en investigación y educación es fundamental, ya que las partes interesadas a menudo poseen un conocimiento limitado de los riesgos. La gestión eficaz del riesgo requiere información personalizada que se alinee con el contexto social y cultural de la comunidad, fomentando un mayor compromiso.

La participación de las partes interesadas desde el principio es esencial para mejorar la preparación. El gobierno desempeña un papel central a la hora de facilitar la colaboración y definir responsabilidades claras. Aunque las empresas turísticas muestran voluntad de colaborar y aceptar restricciones operativas, es poco probable que actúen como \"embajadores\" del proceso de adaptación. Sin embargo, la gobernanza colaborativa puede estimular un mayor interés y participación al abordar factores como la estacionalidad y brindar apoyo financiero cuando sea necesario.

Los resultados del estudio destacan la importancia de generar un sentido de comunidad entre las partes interesadas a través de iniciativas colaborativas. A pesar de centrarse en la playa de Zurriola, los hallazgos pueden informar estrategias más amplias de adaptación al aumento del nivel del mar en áreas costeras similares. Sin embargo, el estudio reconoce sus limitaciones, incluido su alcance geográfico limitado y la necesidad de realizar más investigaciones sobre otras partes interesadas, regiones y diferencias interculturales. Los estudios futuros también pueden explorar el desarrollo empírico de la gobernanza colaborativa para mejorar el proceso de adaptación en los destinos turísticos costeros.
