---
title: 'Digitalización de la cartografía participativa en la gestión integral del riesgo de desastres: potencial y limitaciones de la herramienta Sketch Map para organizaciones humanitarias'
author:
- name: Kimon Letzner
  affiliations:
  - Instituto de Tecnología de Geoinformación de Heidelberg, Heidelberg, Alemania
- name: Anne Schauss1
  affiliations:
  - Cruz Roja Colombiana, Bogotá, Colombia
- name: Sabrina Marx y Eduard Giovanni Ruiz Morales
  affiliations:
  - Instituto de Tecnología de Geoinformación de Heidelberg, Heidelberg, Alemania
keywords:
- Conocimiento del riesgo de desastres
- Reducción del riesgo de desastres a nivel comunitario
- Mapeo participativo
- Innovación tecnológica
- Movimiento Internacional de la Cruz Roja y de la Media Luna Roja
abstract: '[[anne.schauss@heigit.org]{.underline}](mailto:anne.schauss@heigit.org)'
categories:
- Sesión 14. Inteligencia artificial, ciencia, tecnología e innovación
---

[[anne.schauss@heigit.org]{.underline}](mailto:anne.schauss@heigit.org)

En la gestión del riesgo de desastres, la cartografía participativa cierra brechas de datos espaciales en las comunidades al integrar el conocimiento local sobre el riesgo. A pesar de la proliferación de herramientas que facilitan la cartografía participativa, la accesibilidad sigue siendo un desafío para las comunidades y los trabajadores humanitarios que no están familiarizados con las tecnologías, como los sistemas de información geográfica. La adopción de la herramienta Sketch Map (SMT), una novedosa herramienta de cartografía participativa, ha crecido en todo el mundo en la comunidad humanitaria. Sin embargo, su potencial y sus limitaciones en el apoyo a las operaciones humanitarias, como durante las caminatas transectas, las evaluaciones de capacidad y la reducción del riesgo de desastres, carecen de un análisis formal basado en datos. Este estudio de caso cualitativo evaluó el avance tecnológico de la SMT examinando su aplicación en evaluaciones de riesgo comunitario y planificación de reducción de riesgo por parte de organizaciones humanitarias. Centrándose en la primera versión abierta y su iteración posterior (SMT 2.0), este estudio evaluó las fortalezas, deficiencias y mejoras dentro de la Evaluación Mejorada de Vulnerabilidad y Capacidad del Movimiento Internacional de la Cruz Roja y de la Media Luna Roja. Los hallazgos revelaron el potencial de la SMT para formalizar, visualizar, recopilar y discutir el conocimiento local, las percepciones de riesgo y las preferencias durante las caminatas transectas y el mapeo grupal, fusionando la recopilación manual de datos con el análisis y almacenamiento digitales para mejorar el mapeo comunitario y la toma de decisiones a través de la digitalización. Sin embargo, la adopción y aplicabilidad de la herramienta en varios escenarios enfrentó limitaciones debido a restricciones en las funciones del software y la usabilidad, que se abordaron parcialmente con la adición de nuevos idiomas y materiales de apoyo al usuario, otra opción de mapa base y modelos de digitalización mejorados. Si bien la SMT 2.0 tiene como objetivo abordar las limitaciones anteriores, se han identificado oportunidades adicionales de crecimiento que requieren una mayor validación mediante investigaciones futuras para garantizar su aplicabilidad en una variedad de tareas humanitarias. Nuestros resultados demuestran los requisitos esenciales para el desarrollo de herramientas de mapeo participativo, haciendo hincapié en la flexibilidad, la adaptabilidad, la compatibilidad con otras herramientas, la comunicación bidireccional y la capacidad de adopción y uso por parte de personas no expertas, lo que permite a la comunidad de riesgo de desastres avanzar en el campo de la identificación y evaluación integradas del riesgo de desastres.
