---
title: Estudio preliminar de isotopía de aguas superficiales y suelos en el páramo de Chingaza y rio Bogotá
author:
- name: Jimmy Alejandro Muñoz
  affiliations:
  - Servicio Geológico Colombiano, Dirección de Asuntos Nucleares
  corresponding: true
  email: jamunoz@sgc.gov.co
- name: Maribel Moreno
  affiliations:
  - Servicio Geológico Colombiano, Dirección de Asuntos Nucleares
- name: Ana Milena Velásquez
  affiliations:
  - Servicio Geológico Colombiano, Dirección de Asuntos Nucleares
- name: Andrea Rocha
  affiliations:
  - Servicio Geológico Colombiano, Dirección de Asuntos Nucleares
  corresponding: true
  email: jamunoz@sgc.gov.co
- name: Mayda Arrieta
  affiliations:
  - Servicio Geológico Colombiano, Dirección de Asuntos Nucleares
- name: Sergio Gaviria
  affiliations:
  - Servicio Geológico Colombiano, Dirección de Asuntos Nucleares
keywords:
- Relaciones isotópicas
- deuterio
- línea meteórica
- ciclo del agua
- Chingaza
abstract: Actualmente la ciudad de Bogotá presenta desabastecimiento de agua potable lo cual perjudica alrededor de 10 millones de habitantes. Conocer la dinámica del agua y suelos en los principales afluentes
  como los son el embalse de chuza y el rio Bogotá, es fundamental para poder generar políticas y normatividad en torno a la protección de estos ecosistemas. En la última década, las herramientas isotópicas
  como los isotopos de H-2 y O-18, han sido utilizadas para poder entender los componentes del ciclo del agua, evaluar mejor la cantidad, la calidad y la sostenibilidad del agua. El isotopo de C-13 es utilizado
  como biomarcador ya que aporta información de las condiciones ambientales, climatológicas, tipo y humedad del suelo, así como del tipo de vegetación que se desarrolló en estas zonas de estudio y el N-15
  es utilizado como trazador de origen para diferenciación de contaminantes antropogénicos en suelos.
categories:
- Sesión 1. Justicia climática, cambio climático y riesgos emergentes
---

Actualmente la ciudad de Bogotá presenta desabastecimiento de agua potable lo cual perjudica alrededor de 10 millones de habitantes. Conocer la dinámica del agua y suelos en los principales afluentes como los son el embalse de chuza y el rio Bogotá, es fundamental para poder generar políticas y normatividad en torno a la protección de estos ecosistemas. En la última década, las herramientas isotópicas como los isotopos de H-2 y O-18, han sido utilizadas para poder entender los componentes del ciclo del agua, evaluar mejor la cantidad, la calidad y la sostenibilidad del agua. El isotopo de C-13 es utilizado como biomarcador ya que aporta información de las condiciones ambientales, climatológicas, tipo y humedad del suelo, así como del tipo de vegetación que se desarrolló en estas zonas de estudio y el N-15 es utilizado como trazador de origen para diferenciación de contaminantes antropogénicos en suelos.

El Servicio Geológico Colombiano, adelantó una visita al sistema de abastecimiento de agua de Bogotá (Chingaza -- Rio Bogotá) donde se tomaron muestras de suelo y aguas superficiales para poder tener de forma preliminar el comportamiento isotópico de ambas matrices en este sistema durante la época húmeda en que se visitó este sistema. Se recolectaron alrededor de 19 muestra de agua líquida para isotopía de δ^2^H y δ^18^O y 6 muestras de suelo para análisis de isotopos de C-13 y N-15.

Los resultados obtenidos de δ^2^H y δ^18^O de las muestras colectadas presentan las mismas características isotópicas con valores que van desde -74.6 a -81.2 mUr para δ^2^H y de -11.69 a -10.25 mUr para δ^18^O, lo que lleva a pensar que la temporalidad y procedencia del agua es la misma. Las muestras de agua lluvia presentan un alto proceso de reciclaje local, donde se experimentan evaporaciones y precipitaciones sucesivas del agua analizada y una muestra de agua presentó un proceso de evaporación marcado, lo que hace que se ubique por debajo de las líneas meteóricas.

Se observa que los resultados de las relaciones isotópicas de carbono en suelos se ubican entre -27,43 ‰ ± 0,28 ‰ y -23,84 ‰ ± 0,25 ‰, lo cual permite distinguir el tipo de material vegetal de la que se derivó la materia orgánica analizada, ya que firmas isotópicas entre -30 ‰ y -24 ‰ para δ^13^C son correspondientes de plantas que fueron formadas por medio del ciclo de formación C3 o Ciclo de Calvin. Los resultados isotópicos de nitrógeno (δ^15^N) entre 3,3‰ ± 0,1 ‰ y 5,2 ‰ ± 0,1 ‰, permiten concluir que se encuentran dentro del intervalo típico de relación isotópica para muestras corresponden a plantas que fueron formadas por medio del ciclo fotosintético C3 o Ciclo de Calvin (Glaser, 2005) (Raghumani, 2021).
