---
title: ¿Estoy en riesgo si ocurre un sismo?
author:
- name: Ana Beatriz Acevedo Jaramillo
  affiliations:
  - Profesor tiempo completo, Área de Territorios y Ciudades, Universidad EAFIT, aaceved14@eafit.edu.co(mailto:aaceved14@eafit.edu.co)
keywords:
- Riesgo sísmico
- percepción del riesgo
- transmisión de conocimiento
abstract: La sesión estuvo dirigida al público en general y tuvo como objetivo generar un espacio de diálogo con los asistentes para responder dudas sobre los sismos, los componentes del riesgo sísmico,
  la gestión del riesgo, entre otros aspectos relevantes. En la sesión se consultó a los asistentes sobre inquietudes, dudas, mitos, etc., relacionados con los sismos. Estas inquietudes fueron la base para
  el desarrollo de la sesión (tal y como ocurre en el desarrollo del taller de sensibilización con la comunidad) y fueron resueltas con el apoyo de un video desarrollado para el taller que presentó conceptos
  básicos de amenaza y riesgo sísmico, y con las intervenciones de los moderadores. Adicionalmente, los moderadores explicaron i) una actividad de reconocimiento de las características de las viviendas
  de los asistentes y el entendimiento de su capacidad de resistir fuerzas sísmicas, y ii) la comprensión de cómo actuar de manera efectiva ante un evento sísmico.
categories:
- Sesiones Especiales
---

**Sobre la sesión:** La sesión estuvo dirigida al público en general y tuvo como objetivo generar un espacio de diálogo con los asistentes para responder dudas sobre los sismos, los componentes del riesgo sísmico, la gestión del riesgo, entre otros aspectos relevantes. En la sesión se consultó a los asistentes sobre inquietudes, dudas, mitos, etc., relacionados con los sismos. Estas inquietudes fueron la base para el desarrollo de la sesión (tal y como ocurre en el desarrollo del taller de sensibilización con la comunidad) y fueron resueltas con el apoyo de un video desarrollado para el taller que presentó conceptos básicos de amenaza y riesgo sísmico, y con las intervenciones de los moderadores. Adicionalmente, los moderadores explicaron i) una actividad de reconocimiento de las características de las viviendas de los asistentes y el entendimiento de su capacidad de resistir fuerzas sísmicas, y ii) la comprensión de cómo actuar de manera efectiva ante un evento sísmico.

**Objetivos:** Esta sesión tuvo como objetivo generar capacidades en los asistentes para que puedan aplicar la metodología del taller en sus territorios, buscando que el tema del riesgo sísmico se aborde con las comunidades de una manera clara y sin restricciones. El taller cuenta con recursos disponibles en línea (video y guía del taller) que pueden ser adaptados a las necesidades de diferentes públicos. Se espera que en la sesión los asistentes identifiquen formas alternativas de transmisión del conocimiento sobre el riesgo sísmico de modo que la información pueda llegar a públicos diversos.

**Justificación**: Para afrontar el reto de garantizar que los modelos y resultados de la evaluación del riesgo sísmico sean relevantes para la sociedad, mediante un trabajo interdisciplinario e interinstitucional se desarrolló un taller de sensibilización del riesgo sísmico que busca generar un proceso de cambio en los asistentes, para que, mediante una reflexión crítica, aumenten su resiliencia ante sismos y tengan herramientas para contribuir a la gestión del riesgo sísmico. Entendiendo que la gestión de riesgo es un compromiso de todos, la sesión propuesta busca compartir con los asistentes herramientas que faciliten la apropiación social del conocimiento y que permitan que los ciudadanos tengan la mejor respuesta posible en caso de ocurra un sismo, alineándose de esta manera con el tema de IDRiM 2024 "Comunidades resilientes a los desastres por la vida". La metodología propuesta en la sesión, donde hay una participación activa de los asistentes, genera una forma de aprendizaje dinámica que se espera permita que algunos de los asistentes repliquen el taller en sus territorios. La metodología propuesta es innovadora y diferente a las sesiones planificadas en IDRiM 2024, por lo que se considera puede ser un aporte interesante al evento.
