---
title: Conocer los riesgos de mi territorio me permite salvaguardar vidas; Oi, oi, el tsunami puede venir
author:
- name: Liner F. Salazar Torres
abstract: Ingeniera en Producción Acuícola, Universidad de Nariño. Especialista en Educación con Énfasis en Pedagogía, Universidad Mariana, Pasto; Colombia. Especialista en Gestión Ambiental, Universidad
  del Área Andina, Bogotá; Colombia.
categories:
- Sesión 22. Preparación para una respuesta a múltiples riesgos
---

Ingeniera en Producción Acuícola, Universidad de Nariño. Especialista en Educación con Énfasis en Pedagogía, Universidad Mariana, Pasto; Colombia. Especialista en Gestión Ambiental, Universidad del Área Andina, Bogotá; Colombia.

[[linersitas7@gmail.com]{.underline}](mailto:linersitas7@gmail.com)

La institución Educativa Liceo Nacional Max Seidel está ubicada en el distrito de Tumaco, Nariño, Colombia por estar construida en la isla del Morro, está  expuesta y puede ser afectada por diferentes fenómenos marino costeros, entre algunos los Tsunamis; desde el 2005 que se reorganizo el plan de emergencia escolar se lo ha fortalecido a través de los años con la implementación de nuevas estrategias pedagógicas que faciliten la participación de la comunidad en las acciones de preparación frente a la prevención de riesgos por Tsunami; es así que con el proyecto "Conocer los riesgos de mi territorio me permite salvaguardar vidas; Oí, oí; el Tsunami puede venir", y con el apoyo del Semillero de prevención de riesgos Licenal, se realizan  procesos lúdicos que permiten sensibilizar a la comunidad sobre las recomendaciones a tener presentes cuando se presente un movimiento sísmico (Maremoto),que puede generar un Tsunami. En esta oportunidad las recomendaciones a seguir en un evento de Tsunami se realizan a través del dramatizado; Oí, oí; el Tsunami puede venir; elaborado por la docente del Área de Ciencias del Mar; Liner Fabiola Salazar Torres; El dramatizado apropia la aplicación de la pedagogía crítica de paulo Freire para el fortalecimiento del optimismo transformador en la prevención de riesgo por tsunami en Tumaco, Colombia. Investigación realizada por Carlos Andrés Ríos-Uribe, Ph.D. Profesor Investigador; de la Facultad de Educación de la Universidad de Antioquia combinándola con aspectos culturales propios del territorio que permiten que niños jóvenes adultos y adultos mayores se vean inmersos e interesado en esta iniciativa de preparación y prevención de riesgo. Las danzas autóctonas que se muestran en el dramatizado y la canción mensaje utilizando ritmos del Pacifico colombiano permiten conocer la cultura y prepararse ante un riesgo inminente para esta población como son los Tsunamis.

**Palabras claves:** Tsunami, Riesgo, Prevención, Semillero, Salvaguardar.
