---
title: 'Amazonia en llamas: Gobernanza comunitaria y estrategias internacionales'
keywords:
- incendios forestales
- manejo integral del fuego
- políticas
- gobernanza
abstract: Subdirectora para la reducción del riesgo, Unidad Nacional para la Gestión del Riesgo de Desastres
categories:
- Sesión 21. Amazonia, comunidades indígenas y locales
---

Subdirectora para la reducción del riesgo, Unidad Nacional para la Gestión del Riesgo de Desastres

\*Autora de contacto: correo-e: maria.meza@gestiondelriesgo.gov.co

\[Transcripción\] La falta de gestión del paisaje y el cambio climático han incrementado la frecuencia e intensidad de los incendios forestales en la Amazonía. Se ha generado un ciclo de retroalimentación positiva, en el que los incendios emiten CO₂, alteran la estructura de la vegetación y aumentan la probabilidad de nuevos incendios. Los focos de deforestación coinciden con las áreas de mayor actividad agrícola y se encuentran fuera de zonas protegidas y territorios indígenas. Los incendios forestales en la cuenca amazónica responden a diferentes impulsores según la región. En Brasil, están vinculados a la expansión de cultivos como la soja, mientras que en Colombia se relacionan con el acaparamiento de tierras. La percepción actual del fuego ha llevado a la implementación de políticas restrictivas y planes de gestión desarticulados, lo que ha exacerbado conflictos socioambientales. Sin embargo, no todos los fuegos son perjudiciales. La Amazonía no es un ecosistema homogéneo; abarca desde páramos y grandes ciudades hasta sabanas donde el fuego es clave para el mantenimiento ecológico. Por ello, su definición no debe ser simplista ni reducirse a la noción de incendio. El fuego es un elemento esencial para la seguridad alimentaria y una herramienta de manejo territorial en comunidades indígenas y campesinas. El incendio ocurre cuando el fuego se descontrola, requiriendo medidas de contención. Es fundamental adoptar un enfoque integral que considere el papel ecológico del fuego, la diversidad cultural y las relaciones socioambientales. La gestión del riesgo es un proceso social que debe incluir a las comunidades y promover políticas como las brigadas comunitarias de manejo integral del fuego. Se ha creado la red amazónica para el manejo integral del fuego como un llamado internacional en respuesta a los grandes incendios de 2019. Se resumen los llamados internacionales desde 1997 hasta 2023.
