---
title: Evolución y retos de la gestión del riesgo en los instrumentos de planificación territoriales de Colombia
author:
- name: Marco Gamboa Ramírez
  affiliations:
  - Ingeniero Geólogo, Universidad Nacional, Medellín, Colombia
  corresponding: true
  email: mgamboa@eafit.edu.co
keywords:
- Gestión del riesgo
- ordenamiento territorial
- planeación
abstract: La gestión del riesgo en la planificación en Colombia se remonta a finales de los años 80, casi de manera simultánea con la expedición del Decreto Ley 919 de 1989 Por el cual se organiza el Sistema
  Nacional para la Prevención y Atención de Desastres se expide la Ley 9 de 1989 sobre planes integrales de desarrollo, donde se señala que los municipios deben reservar tierras necesarias para la reubicación
  de asentamientos en riesgo, se establecía la posibilidad expropiar lotes para la reubicación de estos asentamientos y se generaba la necesidad de realizar un inventario de asentamientos humanos que presentaran
  alto riesgo por parte de los municipios.
categories:
- Sesión 1. Justicia climática, cambio climático y riesgos emergentes
---

La gestión del riesgo en la planificación en Colombia se remonta a finales de los años 80, casi de manera simultánea con la expedición del Decreto Ley 919 de 1989 Por el cual se organiza el Sistema Nacional para la Prevención y Atención de Desastres se expide la Ley 9 de 1989 sobre planes integrales de desarrollo, donde se señala que los municipios deben reservar tierras necesarias para la reubicación de asentamientos en riesgo, se establecía la posibilidad expropiar lotes para la reubicación de estos asentamientos y se generaba la necesidad de realizar un inventario de asentamientos humanos que presentaran alto riesgo por parte de los municipios.

La expedición de la ley 388 de 1997, genera un cambio significativo en la planificación del territorio, y esta norma de manera implícita, integró las normatividades del Sistema Nacional Ambiental y del Sistema Nacional de Planificación. Sin embargo, la gestión del riesgo y sus alcances en los nuevos instrumentos denominados Planes de ordenamiento territorial no eran claros. Simplemente se señalaba la necesidad de evaluar la amenaza, la vulnerabilidad y el riesgo, pero no se definió para que fenómenos y como se incorporaba, más allá de señalar que las zonas de amenaza alta eran suelo de protección y de la necesidad de reubicar los asentamientos en riesgo no mitigable.

En el año 2014 se expide el decreto 1807, sobre la incorporación de la gestión del riesgo en el ordenamiento, para muchos una norma necesaria para evitar la anarquía en los procesos de concertación de los planes con las autoridades ambientales, para otros, una norma con una exigencia técnica que encarecía y dificultaba aún más la posibilidad de los municipios y distritos de revisar sus instrumentos de planificación.

En todo este tiempo, desde el punto de vista técnico se han generado grandes avances. Pasamos de aplicar métodos heurísticos en las zonificaciones de amenaza y hoy principalmente utilizamos métodos estadísticos, determinísticos, probabilísticos, entre otros. Se tienen metodologías por parte del SGC para amenazas por movimientos en masa y avenidas torrenciales, pero, sobre todo, la gestión dejo de ser un tema exclusivo de las ciencias de la tierra y la ingeniería civil, para transcender en la multidisciplinariedad. Aún falta camino por recorrer, falta integrar otras amenazas, otros fenómenos, principalmente de tipo tecnológico, y quizás, debemos concentrarnos un poco más en la vulnerabilidad en las nuevas etapas del ordenamiento territorial.
