---
title: Análisis de construcciones Histórico- culturales sobre amenazas socio-naturales y vulnerabilidades sociales. Elementos para la gestión del riesgo en Colombia
author:
- name: Yolanda T. Hernández
keywords:
- Etnografía
- imaginarios sociales
- fenómenos amenazantes
abstract: Docente Titular Universidad Distrital Francisco José de Caldas, Bogotá D.C., Colombia,
categories:
- Sesión 12. Percepción del riesgo, comportamiento humano y cultura
---

Docente Titular Universidad Distrital Francisco José de Caldas, Bogotá D.C., Colombia,

[[ythernandezp@udistrital.edu.co]{.underline}](mailto:ythernandezp@udistrital.edu.co)

Las construcciones culturales e interpretaciones que los individuos realizan sobre los fenómenos amenazantes y sus condiciones de vulnerabilidad constituyen un amplio campo de conocimiento para la gestión del riesgo. Las percepciones, imaginarios y sentires de las poblaciones asentadas en zonas de riesgo evidencian la necesidad de considerar enfoques diferenciales para la construcción de políticas y estrategias que busquen mitigar el riesgo y proyectar territorios más seguros y sustentables. A pesar de los valiosos avances en el conocimiento del riesgo, de los avances tecnológicos y de un marco normativo enfocado a su reducción, en Colombia se hace evidente la existencia cíclica de un patrón de desastres, por tanto es pertinente avanzar en el conocimiento del riesgo para conocer las elaboraciones culturales  que las comunidades hacen sobre los fenómenos que los afectan, este conocimiento se constituye en un insumo relevante para una gestión integral del riesgo y el fortalecimiento de estrategias de corresponsabilidad en su gestión. De acuerdo con ello, se plantea como principal objetivo, el presentar un análisis sobre los imaginarios y percepciones de poblaciones asentadas en zonas de influencia de fenómenos amenazantes como erupciones volcánicas, inundaciones y deslizamientos en diferentes regiones del país. Como principal resultado se plantea un modelo conceptual que permita la articulación de conocimientos locales y conocimientos científicos a partir de las construcciones culturales sobre amenaza, vulnerabilidad y riesgo. Esta perspectiva enriquece las discusiones sobre comprensión de la naturaleza y permite aproximarse a las visiones no binarias que construyen comunidades en relación con sus entornos.
