---
title: Qué es la vivienda resiliente con enfoque comunitario?
author:
- name: Adriana Duque Pardo
  affiliations:
  - Build Change, Coordinador de proyectos para Colombia
- name: Manuela Pinilla Rodríguez
  affiliations:
  - Build Change, Directora de programas América Latina
keywords:
- Viviendas vulnerables
- Riesgo sísmico
- Resiliencia comunitaria
- Déficit habitacional
- Reducción del riesgo
abstract: Build Change lideró una serie de actividades para fortalecer las capacidades de los participantes en la evaluación y mejora de viviendas vulnerables ante los desastres y el cambio climático. En
  primer lugar, se estableció un contexto global sobre la vulnerabilidad de las viviendas mediante preguntas participativas, destacando la necesidad de intervenir la vivienda existente de autoconstrucción.
  Posteriormente, se llevó a cabo una charla sobre el escenario específico de Colombia, analizando la relación entre la vulnerabilidad de la vivienda y el impacto potencial en el PIB del país ante eventos
  naturales de gran magnitud. Tras esta inmersión inicial, se realizó un ejercicio interactivo en el que los asistentes compartieron sus experiencias y comprendieron los aspectos técnicos, sociales y financieros
  de una vivienda resiliente. Estas percepciones fueron contrastadas con los datos recopilados por Build Change a partir de sus colaboraciones con comunidades en Colombia. Además, se presentaron los ocho
  factores clave que contribuyen a la resiliencia de una vivienda, seguidos por un estudio de caso práctico. En este, los participantes identificaron las vulnerabilidades de una vivienda real y propusieron
  soluciones para mejorar su resiliencia. Finalmente, Build Change expuso las herramientas disponibles para abordar esta problemática y promover la construcción de comunidades y viviendas más resilientes,
  cerrando así la sesión con un enfoque práctico y soluciones tangibles.
categories:
- Sesiones Especiales
---

**Sobre la sesión:** Build Change lideró una serie de actividades para fortalecer las capacidades de los participantes en la evaluación y mejora de viviendas vulnerables ante los desastres y el cambio climático. En primer lugar, se estableció un contexto global sobre la vulnerabilidad de las viviendas mediante preguntas participativas, destacando la necesidad de intervenir la vivienda existente de autoconstrucción. Posteriormente, se llevó a cabo una charla sobre el escenario específico de Colombia, analizando la relación entre la vulnerabilidad de la vivienda y el impacto potencial en el PIB del país ante eventos naturales de gran magnitud. Tras esta inmersión inicial, se realizó un ejercicio interactivo en el que los asistentes compartieron sus experiencias y comprendieron los aspectos técnicos, sociales y financieros de una vivienda resiliente. Estas percepciones fueron contrastadas con los datos recopilados por Build Change a partir de sus colaboraciones con comunidades en Colombia. Además, se presentaron los ocho factores clave que contribuyen a la resiliencia de una vivienda, seguidos por un estudio de caso práctico. En este, los participantes identificaron las vulnerabilidades de una vivienda real y propusieron soluciones para mejorar su resiliencia. Finalmente, Build Change expuso las herramientas disponibles para abordar esta problemática y promover la construcción de comunidades y viviendas más resilientes, cerrando así la sesión con un enfoque práctico y soluciones tangibles.

**Objetivos:** Ofrecer a los asistentes herramientas prácticas y conocimientos para abordar la problemática de vivienda inadecuada en Colombia, promoviendo así la construcción de comunidades y viviendas más seguras y preparadas frente a desastres naturales

**Justificación**: Esta sesión permitió analizar el escenario de Colombia frente a los riesgos de desastres naturales, especialmente en comunidades y viviendas vulnerables. Según las cifras del DANE de 2021, en los últimos tres años, cerca de 3.977.000 hogares colombianos viven en déficit cualitativo, lo que significa viviendas sin una estructura adecuada, espacios habitables y acceso a servicios públicos. Además, se estima que más del 65% de las construcciones en Colombia carecen de sistemas estructurales adecuados para resistir terremotos. Por ejemplo, en Bogotá, según datos del IDIGER, el porcentaje aumenta al 70%; mientras que en Medellín es del 61% y en Cali del 70%, según el Global Earthquake Modelling (GEM). Esto implica que más de seis millones de viviendas en Colombia son vulnerables. Considerando que más del 80% de la población habita en zonas de amenaza sísmica media o alta, es evidente la necesidad de promover comunidades y viviendas resilientes. Esta promoción no solo busca mejorar las condiciones de vida de millones de personas, sino también reducir el riesgo de pérdidas humanas y económicas ante desastres naturales. La intervención temprana y sistemática en la construcción y mejora de viviendas puede mitigar este riesgo y promover el bienestar de las comunidades colombianas.
