---
title: 'Desafíos de la Adaptación Costera: Enfoque Basado en Ecosistemas en el Caribe Colombiano'
author:
- name: Johan C. Casadiego Estévez
  affiliations:
  - Programa de Geociencias Marinas y costeras-GEO, Instituto de Investigaciones Marinas y Costeras "José Benito Vives de Andréis" (Invemar), Santa Marta, Colombia.
  corresponding: true
  email: david.morales@invemar.org.co
- name: David F. Morales Giraldo
  affiliations:
  - Programa de Geociencias Marinas y costeras-GEO, Instituto de Investigaciones Marinas y Costeras "José Benito Vives de Andréis" (Invemar), Santa Marta, Colombia.
- name: Constanza Ricaurte Villota
  affiliations:
  - Programa de Geociencias Marinas y costeras-GEO, Instituto de Investigaciones Marinas y Costeras "José Benito Vives de Andréis" (Invemar), Santa Marta, Colombia.
keywords:
- Medidas de Adaptación Basada en Ecosistemas
- Sistemas costeros
- Sistema de monitoreo
- Soluciones Basadas en Naturaleza
abstract: David F. Morales Giraldo^1^, [[david.morales@invemar.org.co]{.underline}](mailto:david.morales@invemar.org.co)
categories:
- Sesión 20. Capacidad adaptativa y reducción de la vulnerabilidad ante riesgos ambientales y climáticos
---

David F. Morales Giraldo^1^, [[david.morales@invemar.org.co]{.underline}](mailto:david.morales@invemar.org.co)

Constanza Ricaurte Villota^1^ [[constanza.ricaurte@invemar.org.co]{.underline}](mailto:constanza.ricaurte@invemar.org.co)

Los sistemas costeros enfrentan una creciente vulnerabilidad debido a la influencia combinada de eventos extremos, desarrollo y crecimiento poblacional, cambios geomorfológicos y aumento del nivel del mar. El 22,3% de la población está concentrada en el litoral caribe colombiano, lo que resulta en 9.86 millones de habitantes, particularmente expuestos a las dinámicas costeras. Este escenario ha estimulado la búsqueda de medidas de adaptación al cambio climático, donde las Soluciones basadas en naturaleza (SbN) emergen como una opción prometedora para reducir los riesgos. Las SbN se basan en el aprovechamiento de características naturales de los ecosistemas y soluciones técnicas para reducir la energía hidrodinámica en el sistema costero. Sin embargo, existe incertidumbre sobre metodologías de monitoreo, beneficios y efectividad en diversas escalas espacio-temporales. Se desarrolló el Sistema de Monitoreo de la Erosión Costera y Medidas de Adaptación basadas en Ecosistemas (SMEC-MAbE) en los departamentos de La Guajira, Magdalena, Córdoba y Antioquia. Los principales aportes se basan en un esquema de monitoreo socioambiental compuesto por 8 índices o indicadores implementados que reflejan el estado a partir de calificaciones en escala semáforo. Además, se capacitó a 12 funcionarios de las CARs y 148 miembros de comunidades. También se cartografiaron 126 iniciativas a lo largo del litoral. Los resultados demuestran la oportunidad de aunar esfuerzos para monitorear, visualizar, analizar y almacenar las medidas MAbE en la zona costera. El desarrollo de esquemas de monitoreo es un punto de partida para aumentar el conocimiento sobre la evolución de socioecosistemas costeros reduciendo la incertidumbre en cuanto a la función y efectividad de las SbN para la protección del litoral. La complejidad del sistema y la creciente iniciativa de desarrollar alternativas para la protección de bienes y servicios exigen la creatividad científica y un enfoque basado en la ciencia de la naturaleza.
