---
title: Gestión del conocimiento, prevención y reducción del riesgo a nivel veredal, utilizando herramientas S.I.G y acciones practicas a nivel de bioingeniería para la mitigación
author:
- name: Edgar Armando Malpica Correa
  corresponding: true
  email: armandomalpicacorrea@gmail.com
abstract: En el marco de la gestión del riesgo nacional, el mayor reto ha sido la prevención como principio para la reducción del mismo, el territorio nacional abarca una dinámica por distintos tipos de
  relieves, pisos térmicos, características morfológicas, actividades antrópicas entre muchas más que hacen cada lugar específico para acertar en la elaboración de la zonificación de amenaza de manera más
  local, condicionado a lo extensos que son las administraciones municipales y que de la mano van con los recursos para elaborar un trabajo de identificación o conocimiento, actualmente se pueden realizar
  medidas del gestión del riesgo a nivel de veredas o juntas de acción comunal brindando paso a paso metodologías para que ellos elaboren los propios mapas de amenaza con herramientas digitales gratis,
  analicen la vulnerabilidad propia según la magnitud de las amenazas, clasifiquen el riesgo y realicen acciones de bioingeniería sencillas para la prevención como la recuperación de cobertura vegetal,
  manejo de escorrentía, estabilización de taludes, alertas tempranas. Los puntos que requieran mayor detalle por la complejidad de los eventos naturales puedan ser llevados a las administraciones municipales
  para su gestión e inclusión en el ordenamiento territorial. Conocimiento del riesgo, Eventos naturales, Históricos de eventos, Vulnerabilidad, Reducción del riesgo.
categories:
- Sesión 19. Participación comunitaria y ONGs
---

En el marco de la gestión del riesgo nacional, el mayor reto ha sido la prevención como principio para la reducción del mismo, el territorio nacional abarca una dinámica por distintos tipos de relieves, pisos térmicos, características morfológicas, actividades antrópicas entre muchas más que hacen cada lugar específico para acertar en la elaboración de la zonificación de amenaza de manera más local, condicionado a lo extensos que son las administraciones municipales y que de la mano van con los recursos para elaborar un trabajo de identificación o conocimiento, actualmente se pueden realizar medidas del gestión del riesgo a nivel de veredas o juntas de acción comunal brindando paso a paso metodologías para que ellos elaboren los propios mapas de amenaza con herramientas digitales gratis, analicen la vulnerabilidad propia según la magnitud de las amenazas, clasifiquen el riesgo y realicen acciones de bioingeniería sencillas para la prevención como la recuperación de cobertura vegetal, manejo de escorrentía, estabilización de taludes, alertas tempranas. Los puntos que requieran mayor detalle por la complejidad de los eventos naturales puedan ser llevados a las administraciones municipales para su gestión e inclusión en el ordenamiento territorial. Conocimiento del riesgo, Eventos naturales, Históricos de eventos, Vulnerabilidad, Reducción del riesgo.

Desde la elaboración y firma del decreto 1807 de 2014, participe en la elaboración de los estudios básicos de amenaza en 26 municipios de Boyacá y Cundinamarca todos con distintas características de relieves, cantidad de habitantes y climas, en el componente social para el levantamiento de la información histórica, elaboración de mapas sociales, caracterización de eventos naturales, georreferenciación. Los cuales en el desarrollo de los modelos de mapas de amenaza son de importancia para calibrar los resultados finales.
