---
title: El papel de los modelos de catástrofes como el Modelo Público de Pérdidas por Huracanes de Florida para garantizar comunidades resilientes a los desastres
author:
- name: Jean-Paul Pinelli
  affiliations:
  - Instituto Tecnológico de Florida, Melbourne, Estados Unidos
  corresponding: true
  email: pinelli@fit.edu
- name: Kurt Gurley
  affiliations:
  - Universidad de Florida, Gainesville, Estados Unidos
keywords:
- Modelo de catástrofe
- daño
- mitigación
- resiliencia
abstract: Presentaremos un modelo de catástrofe de última generación establecido, el Modelo Público de Pérdidas por Huracanes de Florida (FPHLM), y describiremos los avances recientes en el modelado del
  riesgo de huracanes para edificios residenciales, tanto de baja como de mediana y gran altura. El FPHLM, como muchos otros modelos de catástrofes, se desarrolló principalmente con fines de seguros. En
  el módulo de vulnerabilidad del FPHLM, una metodología basada en componentes compara las cargas inducidas por el viento en los componentes externos con su capacidad de resistencia, para producir estimaciones
  de daños externos mientras utiliza la física de la entrada, distribución y propagación del agua de lluvia, para proporcionar la base para las proyecciones de daños interiores y de contenido (Wei et al.,
  2024; Silva de Abreu et al., 2020). El modelo combina estimaciones de la velocidad del viento, el impacto de escombros, la lluvia que golpea y la escorrentía superficial impulsada por el viento, los defectos
  y las brechas de la envoltura, la distribución y propagación del agua en el interior y los análisis de costos de los componentes para proyectar los daños en la envoltura, el interior y el contenido. El
  modelo se extiende a los gastos relacionados con el tiempo (TRE), también conocidos como gastos de vida adicionales (ALE) o costos de interrupción de negocios (BIC) (Wei et al., 2023).
categories:
- Sesión 3. Explorando las amenazas marino costeras
---

Presentaremos un modelo de catástrofe de última generación establecido, el Modelo Público de Pérdidas por Huracanes de Florida (FPHLM), y describiremos los avances recientes en el modelado del riesgo de huracanes para edificios residenciales, tanto de baja como de mediana y gran altura. El FPHLM, como muchos otros modelos de catástrofes, se desarrolló principalmente con fines de seguros. En el módulo de vulnerabilidad del FPHLM, una metodología basada en componentes compara las cargas inducidas por el viento en los componentes externos con su capacidad de resistencia, para producir estimaciones de daños externos mientras utiliza la física de la entrada, distribución y propagación del agua de lluvia, para proporcionar la base para las proyecciones de daños interiores y de contenido (Wei et al., 2024; Silva de Abreu et al., 2020). El modelo combina estimaciones de la velocidad del viento, el impacto de escombros, la lluvia que golpea y la escorrentía superficial impulsada por el viento, los defectos y las brechas de la envoltura, la distribución y propagación del agua en el interior y los análisis de costos de los componentes para proyectar los daños en la envoltura, el interior y el contenido. El modelo se extiende a los gastos relacionados con el tiempo (TRE), también conocidos como gastos de vida adicionales (ALE) o costos de interrupción de negocios (BIC) (Wei et al., 2023).

El FPHLM es un modelo multirriesgo (Wei et al., 2024) con un módulo independiente que proyecta pérdidas debido a la combinación de viento, impacto de escombros y lluvia (Pita et al., 2016; Johnson et al., 2018) y otro módulo que proyecta pérdidas debido a inundaciones costeras e interiores (Paleo-Torres et al., 2020). Se está desarrollando un tercer módulo que proyecta pérdidas debido a la caída de árboles. Las pérdidas de las diferentes amenazas se pueden combinar.

La discusión describirá algunos de los desafíos asociados con el desarrollo de estos modelos de vulnerabilidad, las fuentes de incertidumbres y su propagación. Analizaremos cómo un enfoque basado en componentes, fundamentado en la física del problema para el modelado de la vulnerabilidad de los daños exteriores, interiores y de los contenidos, y la TRE pueden facilitar la evaluación de estrategias de resiliencia para comunidades enteras, incluyendo la duración de los tiempos de recuperación, la cantidad de escombros generados y la rentabilidad de las medidas de mitigación (Paleo-Torres et al., 2022). Estos modelos también pueden utilizarse para investigar el impacto del aumento del nivel del mar y el cambio climático. No sólo las aseguradoras pueden utilizar estos modelos para proyectar las pérdidas, sino que los gestores de emergencias y los planificadores urbanos pueden utilizar las proyecciones de daños y los tiempos de recuperación para caracterizar la resiliencia de las comunidades costeras. El debate se centra en el caso de los huracanes, pero podría extenderse a cualquier otro tipo de modelo de catástrofe.
