---
title: 'Voces Diversas e Inclusivas, un Futuro Resiliente: Participación de Mujeres, personas con movilidad reducida, comunidad LGBT y enfoque étnico en la Gestión del Riesgo de Desastres y cambio climático'
author:
- name: Jeisson Orlando Garcia Orjuela
  affiliations:
  - Unidad Nacional para la Gestión del Riesgo de Desastres, Subdirección para el Conocimiento del Riesgo, jeisson.garcia@gestiondelriesgo.gov.co
- name: Rosa María Juarez Cobeñas
  affiliations:
  - Presidenta de la red inclusiva de gestión de riesgos desastres y discapacidad de América Latina y el caribe, RED GIRDD-LAC, Perú
- name: Heidy Katerine Cataño
  affiliations:
  - Bomberos Indígenas Riosucio, Caldas, Colombia
- name: Michael Méndez
  affiliations:
  - University of California, Berkeley, Estados Unidos
- name: Funda Atun
  affiliations:
  - University of Twente, Países Bajos
keywords:
- Diversidad
- equidad
- inclusión
- enfoque inclusivo
abstract: Se abordó la importancia de la participación de jóvenes, mujeres, la comunidad LGBT y grupos étnicos en la gestión del riesgo de desastres (GRD) y la adaptación al cambio climático en Colombia.
  A través de un conversatorio, los invitados/expertos compartieron experiencias, estrategias y mejores prácticas para integrar un enfoque inclusivo en la planificación y ejecución de políticas de gestión
  del riesgo.
categories:
- Sesiones Especiales
---

**Sobre la sesión:** Se abordó la importancia de la participación de jóvenes, mujeres, la comunidad LGBT y grupos étnicos en la gestión del riesgo de desastres (GRD) y la adaptación al cambio climático en Colombia. A través de un conversatorio, los invitados/expertos compartieron experiencias, estrategias y mejores prácticas para integrar un enfoque inclusivo en la planificación y ejecución de políticas de gestión del riesgo.

**Objetivos:** 1) Fomentar la inclusión. Impulsar la participación de las personas con movilidad reducida, mujeres, la comunidad LGBT y grupos étnicos en la gestión del riesgo de desastres y el cambio climático. Compartir conocimientos y experiencias. 2) Presentar estudios de caso, mejores prácticas y experiencias que han demostrado ser eficaces dentro del contexto del Enfoque Diferencial y de Género en la Gestión del Riesgo de Desastres, con el fin de desarrollar estrategias y herramientas para una gestión del riesgo y adaptación al cambio climático inclusivas que fortalezcan la resiliencia de todas las comunidades.

Justificación**:** Esta sesión reconoció que la resiliencia efectiva solo se puede lograr mediante la inclusión de todas las voces y perspectivas en la gestión del riesgo de desastres. Las mujeres, las personas con movilidad reducida, la comunidad LGBTIQ+ y los grupos étnicos a menudo enfrentan barreras adicionales y vulnerabilidades específicas que aumentan su riesgo en situaciones de desastre. Al proporcionar un espacio para discutir y abordar estas cuestiones, esta sesión contribuye a la creación de prácticas más equitativas y efectivas. El Marco de Sendai para la Reducción del Riesgo de Desastres 2015-2030 destaca la importancia de una perspectiva inclusiva y de género en la reducción del riesgo. Además, enfatiza la necesidad de empoderar a las comunidades y fortalecer su capacidad de resiliencia mediante la participación de todos los sectores de la sociedad. Además, el enfoque en compartir conocimientos y mejores prácticas fomenta la colaboración internacional y el aprendizaje mutuo, lo cual es esencial para enfrentar los desafíos globales del cambio climático y los desastres naturales. En última instancia, esta sesión buscó empoderar a las comunidades y asegurar que sus necesidades y capacidades sean integradas en todas las fases de la gestión del riesgo, desde la prevención hasta la recuperación, promoviendo así una resiliencia verdaderamente inclusiva y sostenible.
