---
title: 'Los estudios de riesgo volcánico en Colombia: Más allá de modelamientos matemáticos'
author:
- name: John Makario Londoño Bonilla.^1 ^
  affiliations:
  - Geólogo, MSc, PhD, Servicio Geológico Colombiano, Bogotá, Colombia.
  corresponding: true
  email: jmakario@sgc.gov.co
keywords:
- Gestión del riego de desastre
- erupción volcánica
- mapa de riesgo volcánico
- riesgo probabilista
- volcán Galeras
abstract: La gestión del riesgo de desastres por erupciones volcánicas en Colombia carece actualmente de normatividad para la elaboración de estudios de amenaza y riesgo volcánico con enfoque hacia el ordenamiento
  territorial.
categories:
- Sesión 8. Percepción del riesgo, comportamiento humano y cultura
---

La gestión del riesgo de desastres por erupciones volcánicas en Colombia carece actualmente de normatividad para la elaboración de estudios de amenaza y riesgo volcánico con enfoque hacia el ordenamiento territorial.

El Servicio Geológico Colombiano (SGC) tiene entre sus funciones la de "proveer información sobre las amenazas y riesgo físico de origen geológico a las instancias y autoridades competentes y a la comunidad, con fines de planificación, ordenamiento territorial y gestión del riesgo". En particular, la información sobre amenaza volcánica ha sido elaborada desde hace décadas por parte del SGC. No obstante, estudios de riesgo volcánico no se habían realizado en Colombia. Recientemente, la Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD) contrató un estudio sobre riesgo volcánico probabilista para el volcán Galeras (VG) (Nariño). Dicho estudio, a criterio del SGC, subvaloró el riesgo, particularmente el riesgo medio, al no considerar información adicional o el estado actual del VG, el cual muestra evidencias de nuevas intrusiones de magma. A raíz de esta situación, y considerando los resultados de los estudios deterministas de amenaza volcánica que ha elaborado el SGC para el VG, se realizó un ajuste a los resultados del estudio de riesgo contratado por la UNGRD, en donde se combinaron los resultados probabilistas y los deterministas, de una manera similar a la usada para la determinación del límite físico de rondas hídricas ya reglamentadas mediante un decreto en Colombia, logrando un mapa de riesgo que puede ser usado como insumo en los planes de ordenamiento territorial en los municipios afectados por la actividad volcánica del VG.

Este trabajo demuestra que, más allá de los resultados de modelos matemáticos de riesgo volcánico, es importante combinar información de diferentes fuentes con el fin de poder generar insumos que permitan tomar decisiones más acertadas y basadas en la evidencia geocientífica.
