---
title: Modelo Nacional de Riesgo Sísmico de Colombia
author:
- name: Monica Arcila Ph.D
keywords:
- Gestión del riesgo
- ordenamiento territorial
- riesgo sísmico
abstract: '[[marcila@sgc.gov.co]{.underline}](mailto:marcila@sgc.gov.co)'
categories:
- Sesión 15. Identificación de riesgos en entornos rurales y urbanos
---

[[marcila@sgc.gov.co]{.underline}](mailto:marcila@sgc.gov.co)

El Modelo Nacional de Riesgo Sísmico (MNRS) es una iniciativa del Servicio Geológico Colombiano, construida en conjunto con 14 universidades colombianas agrupadas bajo la Asociación Colombiana de Facultades de Ingeniería, con la asesoría de dos expertos internacionales y con el apoyo de entidades de gobierno y otras organizaciones públicas y privadas. El MNRS se concibe como un modelo de referencia público y de datos abiertos, que busca aportar al conocimiento y a la gestión del riesgo sísmico en el país, en los niveles nacional y regional. La actual fase del MNRS se enfoca en el sector residencial y, para su desarrollo, se priorizaron 90 centros poblados, que abarcan más del 60% de la población, incluyendo las ciudades capitales. Para estos se desarrollaron modelos de exposición de edificaciones y población a nivel de manzana censal empleando información pública e inspecciones visuales sobre muestras representativas de edificaciones. El costo de reposición se aproximó al costo de construcción estimado de un modelo nacional de costos, también desarrollado para el MNRS. El modelo de vulnerabilidad del MNRS se construyó a partir de la definición de tipologías y de su caracterización constructiva a partir de la conformación de bases de datos de atributos estructurales y arquitectónicos, y de propiedades mecánicas de materiales de construcción. Esto permitió la definición de múltiples arquetipos estructurales para capturar la incertidumbre aleatoria, su modelación numérica y la obtención de funciones de fragilidad y vulnerabilidad sísmica. El riesgo sísmico se evaluó mediante un enfoque probabilístico y por escenarios, de manera tal que los resultados del MNRS puedan ser de utilidad a los procesos de reducción del riesgo, protección financiera, como preparación para el manejo del desastre y reconstrucción. Finalmente, se presentan ejemplos de los resultados que son producidos para cada centro poblado y se discuten sus potenciales aplicaciones en la GRD.
