---
title: Las verdades al aplicar los planes de emergencia y contingencia, los enigmas del valor presupuestal" emergencia por desabastecimiento de agua en la ciudad de Yopal".
author:
- name: Luz Mireya Patiño Salcedo
keywords:
- Plan de emergencia y contingencias
- planta de tratamiento
- Centro de Atención a la Contingencia
abstract: Ingeniera Sanitaria y Ambiental, Especialista en Medio ambiente, Especialista en Seguridad, Master en HSEQ.
categories:
- Sesión 23. Gestión eficaz de recursos y coordinación logística
---

Ingeniera Sanitaria y Ambiental, Especialista en Medio ambiente, Especialista en Seguridad, Master en HSEQ.

Empresa de Acueducto, Alcantarillado y Aseo de Yopal, Colombia.

[[yaremi99@gmail.com]{.underline}](mailto:yaremi99@gmail.com)

Yopal, la capital del Departamento de Casanare, enfrentó una grave crisis de agua, debido a una falla geológica (movimiento en masa de tipo rotacional), que hizo que la planta de tratamiento de agua de capacidad de 400 l/s, quedara totalmente destruida, en el año 2011, conllevando a quedar sin agua, y generado preocupación y dificultades para los habitantes de la ciudad. Actualmente se siguen sorteando inconvenientes para superar en su totalidad la Contingencia. La EAAAY, contaba con un plan de emergencias y contingencias, que nunca se había aplicado, no se conocía la magnitud del costo que se asumiría por ello, la contingencia desencadenó protestas de la comunidad, fallas en la planeación por la premura, inversiones cuantiosas en sistemas de tratamiento, medios de distribución, disturbios por inconformismo de la comunidad al no contar con el servicio de agua potable, y aunado a ello la presencia de rotavirus y enterovirus. Ante esta situación, las autoridades locales, Departamentales y Nacionales, implementaron un plan de choque con medidas para hacer frente a la emergencia, a corto, mediano y largo plazo. Se han realizado inversiones en infraestructuras de captación, pozos profundos, plantas de tratamiento, almacenamiento de agua y distribución por medio de carrotanques, así como en la rehabilitación de pozos de baja producción para el cargue, mantenimiento a los sistemas provisional de tratamiento (Plantas sector de la Vega). Además, se han promovido campañas de concientización sobre el uso eficiente y ahorro del agua, así como la importancia de su conservación. En Yopal se implementó por primera vez tanques de almacenamiento estacionarios, pilas públicas, rutas y microruteo de distribución por medio de carrotanques, aumento intensivo de análisis de calidad de agua y la conformación de un grupo especial llamado CAC- Centro de Atención a la Contingencia. En conclusión, la emergencia por desabastecimiento de agua potable en Yopal durante los años 2011-2022, fue una gran contingencia que afectó a la comunidad. Se tomaron medidas para hacer frente a esta crisis, pero también se evidenció la necesidad de implementar políticas y acciones a largo plazo para garantizar un suministro de agua adecuado y sostenible en la ciudad.
