---
title: Monitoreo participativo para fortalecer el sistema de alertas tempranas comunitarios ante inundaciones y crecientes súbitas en regiones montañosas. Caso de estudio quebrada Manizales, Manizales.
author:
- name: Maria J. Henao Salgado
  affiliations:
  - Estudiante de doctorado en Ingeniería Civil-Departamento de Ingeniería Civil-Universidad Nacional de Colombia, Manizales, Colombia
- name: Pedro A. Hernandez Vasquez
  affiliations:
  - Maestro de Ciencias Naturales, Institución Educativa Superior de Maltería, Manizales, Colombia
- name: Jose H. Duque Corrales
  affiliations:
  - Concejal y Expresidente de la junta de acción comunal del barrio Maltería, Concejo de Manizales, Manizales, Colombia
- name: Jorge J. Vélez Upegui
  affiliations:
  - Profesor titular del Departamento de Ingeniería Civil-Facultad de Ingeniería y Arquitectura-Universidad Nacional de Colombia, Manizales, Colombia
keywords:
- Monitoreo ambiental comunitario
- Sistemas de alerta temprana comunitarios
- Comunidades resilientes
- Sensores de bajo costo
- Ciencia ciudadana
abstract: '[[mjhenaos@unal.edu.co]{.underline}](mailto:mjhenaos@unal.edu.co)'
categories:
- Sesión 24. Sistemas de Alerta Temprana
---

[[mjhenaos@unal.edu.co]{.underline}](mailto:mjhenaos@unal.edu.co)

La incorporación de ciencia ciudadana en los sistemas de alerta temprana comunitarios puede mejorar la eficacia de las alertas ante inundaciones y la resiliencia de las comunidades vulnerables (Buytaert et al., 2014; Njue et al., 2019; Wolff, 2021, 2022). Al empoderar a las poblaciones vulnerables para que aporten datos en tiempo real a través del monitoreo participativo, estos sistemas cierran brechas en la infraestructura de monitoreo tradicional, proporcionando información crucial sobre la dinámica de las inundaciones localizadas y permitiendo esfuerzos de respuesta más oportunos y específicos. Los estudios han demostrado que la integración de la ciencia ciudadana no solo mejora la recopilación y el análisis de datos, sino que también fomenta el sentido de pertenencia comunitario y la capacidad de adaptación frente a amenazas naturales (Buytaert et al., 2014; Paul & Buytaert, 2018; Shirk & Bonney, 2015). Los sistemas de alerta temprana comunitarios (SATC) a menudo enfrentan desafíos relacionados con equipos, recursos, infraestructura y apoyo institucional limitados. En este estudio, queremos mostrar el co-diseño, puesta en marcha y resultados de un proyecto de monitoreo ambiental participativo y ciencia ciudadana, incluyendo a las comunidades vulnerables y el colegio de la zona ante inundaciones y crecientes repentinas en la quebrada Manizales donde existe un SATC. El proyecto se encuentra en ejecución y trabaja en los frentes de conocimiento del riesgo ante amenazas naturales locales. Construcción de estaciones comunitarias de nivel y lluvia. Diseño e incorporación de sensores de bajo costo de nivel y lluvia en puntos estratégicos. Y finalmente, el programa de sensores comunitarios del agua. La integración de proyectos de ciencia ciudadana en los sistemas de alerta temprana de inundaciones repentinas genera amplios beneficios, como redundancia en la información, mayor conciencia y preparación, y relaciones fortalecidas entre científicos, autoridades y comunidad, fomentando enfoques colaborativos para la reducción del riesgo de desastres.
