---
title: 'Gestión del riesgo orientada a la sostenibilidad: una ruta para mejorar la calidad de vida en las pequeñas ciudades'
author:
- name: Graciela Peters G
  affiliations:
  - Geóloga. Corporación Autónoma Regional del Valle del Cauca -- CVC, Santiago de Cali, Colombia
- name: Arélix A. Ordoñez F
  affiliations:
  - Ingeniera ambiental, Corporación Autónoma Regional del Valle del Cauca -- CVC, Santiago de Cali, Colombia
- name: Andrés F. Trujillo O
  affiliations:
  - Arquitecto, Corporación Autónoma Regional del Valle del Cauca -- CVC, Santiago de Cali, Colombia
keywords:
- zonificación de amenazas
- ordenamiento territorial
- gestión urbana sostenible
- SBN
- calidad de vida
abstract: '[[graciela.peters@cvc.gov.co]{.underline}](mailto:graciela.peters@cvc.gov.co)'
categories:
- Sesión 20. Capacidad adaptativa y reducción de la vulnerabilidad ante riesgos ambientales y climáticos
---

[[graciela.peters@cvc.gov.co]{.underline}](mailto:graciela.peters@cvc.gov.co)

En el marco de la política de ordenamiento territorial algunos municipios han revisado los contenidos de sus planes de ordenamiento territorial procurando la integración transversal de la Gestión del Riesgo de manera gradual en la planificación del territorio bajo modelos de desarrollo sostenible. Dicha tarea ha tropezado con dificultades de tipo funcional, administrativo y financiero que se traducen en bajos presupuestos disponibles, especialmente municipios pequeños (categorías 5 y 6); la falta de personal calificado y los altos costos asociados al conocimiento del riesgo, dificultando la adecuada integración y gestión, la cual se hace más demandante en las zonas urbanas debido a su densidad y alta complejidad de ocupación. Si la sostenibilidad de las ciudades implica la adecuada gestión de riesgo, el primer paso es su inclusión transversal en el desarrollo de estas, presentando instrumentos prácticos que indiquen cómo hacerla efectiva, dado que las intervenciones prospectivas y correctivas de la GdR, integradas con temáticas estructurales para el funcionamiento sostenible de las pequeñas ciudades, se constituyen en herramientas para crear entornos seguros, atractivos, inclusivos y resilientes (OCD 11). Así, la gestión de áreas bajo amenaza o riesgo generalmente deriva en la recuperación de espacios naturales ocupados o degradados. Si esta gestión es adecuadamente direccionada puede generar instrumentos multipropósito que encaminen las ciudades hacia el mejoramiento su calidad ambiental y sostenibilidad en general, a través de la implementación de soluciones basadas en naturaleza, aportando entre otros a la disminución de exposición de los habitantes y sus bienes, la recuperación de los servicios ecosistémicos de los elementos naturales, disminuyendo la pérdida de biodiversidad y generando conectividad con ecosistemas rurales, incrementando índices de espacio público y arbolado y finalmente avanzando en la adaptación al cambio climático a través de la reducción de islas de calor, retención e infiltración de agua, captura de carbono, entre otros.
