---
title: 'Apoyo a la gestión y gobernanza de riesgos de Natech en Colombia: cambios en la conciencia de riesgos mediante un enfoque de juego serio'
author:
- name: Lina M. Parra y Ana M. Cruz
  affiliations:
  - Estudiante de doctorado, Facultad de Ingeniería, Universidad de Kioto, Kioto, Japón
keywords:
- gestión de riesgos
- gobernanza de riesgos
- participación de las partes interesadas
- comunicación de riesgos
- juegos serios
abstract: '[[cruznaranjo.anamaria.2u@kyoto-u.ac.jp]{.underline}](mailto:cruznaranjo.anamaria.2u@kyoto-u.ac.jp)'
categories:
- Sesión 9. Perspectivas de la Gestión de Riesgos Natech
---

[[cruznaranjo.anamaria.2u@kyoto-u.ac.jp]{.underline}](mailto:cruznaranjo.anamaria.2u@kyoto-u.ac.jp)

Los eventos tecnológicos desencadenados por amenazas naturales con la consiguiente liberación de materiales peligrosos se conocen como Natech. Los Natech tienen el potencial de causar impactos graves y extensos en grandes áreas, lo que lleva a enormes daños económicos y ambientales (Kiyohara K, A.M. Cruz, 2016). Estos eventos constituyen un problema complejo y de alta incertidumbre para la gestión y gobernanza del riesgo de desastres, DRM, que requiere la participación de muchas partes interesadas (Aven y Renn, 2010). Para desarrollar e implementar medidas efectivas de reducción del riesgo de desastres (RRD), es necesario abordar la concientización sobre los riesgos y la comunicación entre las partes interesadas (OCDE, 2015). Se ha demostrado que los enfoques descendentes (por ejemplo, conferencias, exposiciones (Charrière et al., 2017) y ascendentes (por ejemplo, obtener conocimiento de las comunidades) pueden lograr la transferencia de conocimiento, pero no son suficientes para reunir a las partes interesadas para el debate. Hoy en día, es bien aceptado que las estrategias de DRM, gobernanza y RRD deben discutirse y se necesita más participación. Los enfoques participativos como los grupos focales o los juegos serios (Aleksandra Solinska-Nowak et al., 2018; Fleming et al., 2020) pueden ser útiles para crear conciencia y reunir a las partes interesadas, proporcionando un espacio para generar confianza. El objetivo del estudio es desarrollar una mejor comprensión del problema de la gestión y gobernanza de riesgos Natech en Colombia, al observar más de cerca los roles de las partes interesadas en el proceso, mediante la realización de talleres de juegos serios. Se seleccionó un juego llamado EGNARIA desarrollado por (Tzioutzios, 2022) como herramienta, y ayudó a producir algunos cambios en la conciencia del riesgo y la confianza de las partes interesadas en sí mismas y en los demás. El objetivo era comprender cómo se llevó a cabo el proceso e identificar formas de mejorarlo para apoyar la gestión y reducción del riesgo de desastres. Este trabajo demostrará que los talleres en los que se utilizaron juegos serios generaron cambios significativos inmediatos en la conciencia de los riesgos, la percepción de los riesgos y los comportamientos de comunicación de los riesgos, y demostraron ser adecuados para promover el diálogo.
