---
title: 'El arte como plataforma para la comunicación, la educación y la concientización sobre los riesgos de desastres: desarrollo de un marco para respuestas a los desastres impulsadas por el arte'
author:
- name: Florence Lahournat
  affiliations:
  - Profesora asociada junior, Instituto de Investigación para la Prevención de Desastres, Universidad de Kioto, Uji, Japón
keywords:
- Comunicación de riesgos
- Conciencia de riesgos
- Arte
- Comunidad
- Enfoques holísticos
abstract: '[[lahournat.florence.3a@kyoto-u.ac.jp]{.underline}](mailto:lahournat.florence.3a@kyoto-u.ac.jp)'
categories:
- Sesión 4. Percepción del riesgo, comportamiento humano y cultura
---

[[lahournat.florence.3a@kyoto-u.ac.jp]{.underline}](mailto:lahournat.florence.3a@kyoto-u.ac.jp)

Si bien el arte ha sido durante mucho tiempo una poderosa herramienta de expresión y comunicación, su potencial en la comunicación de riesgos de desastres sigue siendo relativamente inexplorado. Sin embargo, en los últimos años se ha prestado más atención a los proyectos artísticos, en particular los comunitarios, así como a las producciones artísticas en reacción a los desastres, en particular en los campos de la literatura, las artes escénicas y la cultura pop.

Considerar el arte en relación con los desastres -o en respuesta a ellos- requiere en primer lugar considerar la modalidad de su surgimiento. O, en otras palabras: ¿qué hace que se produzca, cree u organice arte tras los desastres?

Como primer paso de un proyecto más amplio centrado en el arte como una plataforma potencial para la comunicación de riesgos, este artículo intenta responder a esta pregunta, trazando un mapa de los diferentes tipos de expresiones artísticas que surgen después de un desastre y creando una tipología basada en las motivaciones.

Este marco inicial guiará un debate sobre los posibles roles e impactos de las diversas respuestas artísticas (incluidas las artes visuales, las artes escénicas, la literatura) a los desastres, como catalizadores de la comunicación de riesgos, la educación y la conciencia pública. Por último, este artículo abordará los desafíos de crear enfoques integrados de comunicación de riesgos, a los que se espera que el arte (y las producciones artísticas en general) puedan contribuir.
