---
title: 'Continuación de la ciencia de la implementación: actualización del progreso y sugerencias prospectivas'
author:
- name: Norio Okada y Robert Goble
  affiliations:
  - Profesor emérito, Universidad de Kioto, Japón; kyotookanori1104@outlook.jp(mailto:kyotookanori1104@outlook.jp)
keywords:
- Ciencia de la implementación
- resiliencia ante desastres
- gestión integrada del riesgo de desastres
abstract: Desde 2022, los coordinadores, el Prof. Okada y el Prof. Goble, han dirigido dos Sesiones Especiales en las Conferencias Anuales del IDRiM (2022 en Rumania y 2023 en India), centradas en las brechas
  de implementación para fomentar la ciencia de la implementación. Un documento conceptual, debatido en el IDRiM 2022, dio lugar a la publicación de un documento de perspectiva (Okada et al., 2023). Tras
  el IDRiM 2023, se creó un Grupo de Trabajo de IDRiM sobre Ciencia de la Implementación, dirigido por el Prof. Okada. El Grupo de Trabajo involucró a científicos especializados en la implementación a través
  de reuniones en línea, donde seis presentaron casos relacionados con diversos desafíos de implementación. Estos debates han impulsado la comparación de casos y han inspirado un enfoque integrador para
  los estudios de implementación. La sesión especial propuesta buscó fomentar el interés por la investigación, facilitar el intercambio de ideas y fomentar la colaboración en la ciencia de la implementación.
categories:
- Sesiones Especiales
---

**Sobre la sesión:** Desde 2022, los coordinadores, el Prof. Okada y el Prof. Goble, han dirigido dos Sesiones Especiales en las Conferencias Anuales del IDRiM (2022 en Rumania y 2023 en India), centradas en las brechas de implementación para fomentar la ciencia de la implementación. Un documento conceptual, debatido en el IDRiM 2022, dio lugar a la publicación de un documento de perspectiva (Okada et al., 2023). Tras el IDRiM 2023, se creó un Grupo de Trabajo de IDRiM sobre Ciencia de la Implementación, dirigido por el Prof. Okada. El Grupo de Trabajo involucró a científicos especializados en la implementación a través de reuniones en línea, donde seis presentaron casos relacionados con diversos desafíos de implementación. Estos debates han impulsado la comparación de casos y han inspirado un enfoque integrador para los estudios de implementación. La sesión especial propuesta buscó fomentar el interés por la investigación, facilitar el intercambio de ideas y fomentar la colaboración en la ciencia de la implementación.

**Objetivos: 1)** Continuar las sesiones especiales sobre ciencia de la implementación en las conferencias anuales anteriores del IDRiM para fomentar y estimular el interés en la investigación y el intercambio centrados en la implementación; 2) Actualización del progreso del Grupo de Trabajo de IDRiM sobre Ciencia de la Implementación; y 3) Proponer un conjunto de sugerencias, incluyendo el desarrollo de una plataforma (por ejemplo, un sitio web) para la recopilación de casos y sugerencias para el desarrollo de un Catálogo de Brechas de Implementación: una 'base de datos de casos' común, para promover el estudio centrado en la implementación.

**Justificación**: La sesión especial propuesta se alinea con el tema de la conferencia IDRiM 2024, «Comunidades Resilientes ante los Desastres por la Vida». Si bien se ha avanzado enormemente en la comprensión y el conocimiento sobre la resiliencia ante desastres y las comunidades resilientes ante desastres, la implementación efectiva sigue siendo un desafío muy común en cada etapa de la gestión integrada del riesgo de desastres: prevención, mitigación, respuesta a emergencias, recuperación y reurbanización, todas ellas esenciales para el desarrollo de comunidades resilientes ante desastres. Por lo tanto, el IDRiM 2024 ha hecho un llamado explícito a la «integración para cerrar la brecha entre la ciencia y la implementación, a fin de aumentar la usabilidad y el uso del conocimiento para la reducción y gestión del riesgo de desastres, y para promover la investigación y las soluciones de implementación». La sesión especial propuesta responde directamente a este llamado.
