---
title: Propuesta metodológica para la evaluación de la vulnerabilidad sísmica en municipios de bajos recursos
author:
- name: Carlos E. Alvarado Flores
  affiliations:
  - Ingeniero Civil. Esp. Geotecnia Universidad Nacional de Colombia., MSc. en Gestión del Riesgo y Desarrollo, ESING. Consultor independiente. Bogotá, Colombia
  corresponding: true
  email: Ceaf70@gmail.com
- name: Gloria L^.^ Ruiz Peña
  affiliations:
  - Ingeniera Civil, Esp. Geotecnia U.N., Esp. SIG U.D., MSc. en Estudios Sociales de la Ciencia, U.N. Exfuncionaria del Servicio Geológico Colombiano, Consultora independiente, Docente ESING., Bogotá,
    Colombia, gloria.ruiz@esing.edu.co(mailto:gloria.ruiz@esing.edu.co)
keywords:
- Vulnerabilidad sísmica
- Riesgo sísmico
- Metodología
- Semi-cuantitativa
abstract: Colombia se localiza en el área de influencia del cinturón de fuego del Pacífico y por lo tanto la ocurrencia de sismos históricamente ha generado importantes pérdidas de vidas humanas y económicas.
  En las últimas décadas, se han realizado investigaciones y estudios detallados para conocer las condiciones de amenaza y de vulnerabilidad de los elementos expuestos, solo para algunas capitales de departamentos
  y algunos municipios, debido a los altos costos de tales estudios. El conocimiento del riesgo sísmico, a nivel municipal en Colombia, en particular los municipios de menores ingresos (categorías 5 y 6),
  se ha visto limitado por la falta de metodologías simplificadas que permitan evaluar la amenaza y la vulnerabilidad a partir de datos a escalas semidetalladas, a fin de obtener escenarios de riesgo que
  brinden a las autoridades información técnica para tomar decisiones enfocadas a reducir las pérdidas de vidas humanas y económicas.
categories:
- Sesión 5. Modelado y pronóstico de geoamenazas
---

Colombia se localiza en el área de influencia del cinturón de fuego del Pacífico y por lo tanto la ocurrencia de sismos históricamente ha generado importantes pérdidas de vidas humanas y económicas. En las últimas décadas, se han realizado investigaciones y estudios detallados para conocer las condiciones de amenaza y de vulnerabilidad de los elementos expuestos, solo para algunas capitales de departamentos y algunos municipios, debido a los altos costos de tales estudios. El conocimiento del riesgo sísmico, a nivel municipal en Colombia, en particular los municipios de menores ingresos (categorías 5 y 6), se ha visto limitado por la falta de metodologías simplificadas que permitan evaluar la amenaza y la vulnerabilidad a partir de datos a escalas semidetalladas, a fin de obtener escenarios de riesgo que brinden a las autoridades información técnica para tomar decisiones enfocadas a reducir las pérdidas de vidas humanas y económicas.

Se propone una metodología semicuantitativa (semi-c), para los municipios de quinta y sexta categoría, en especial aquellos en zonas de amenaza sísmica intermedia y alta, que corresponden al 81% del total del país. La metodología permite estimar de manera indicativa la respuesta sísmica local del terreno y la vulnerabilidad de las edificaciones de ocupación normal, que conforman el suelo urbano (cabecera municipal y centros poblados), a escalas 1:10.000 o superiores.

La metodología tiene cuatro etapas: la primera es la recopilación de información y alistamiento de los insumos cartográficos básicos y temáticos, la segunda la evaluación del evento amenazante mediante el cálculo del índice de amenaza sismo-geotécnica -IGH, la tercera enfocada a la caracterización y cálculo del índice de vulnerabilidad-IV de las viviendas, y la cuarta la generación de los productos cartográficos de zonificación de la respuesta sísmica y de la vulnerabilidad de las viviendas en la zona de estudio.
