---
title: Uso de tecnologías geoespaciales nuevas y emergentes para mejorar las estadísticas oficiales en Colombia y su potencial uso en la gestión de riesgos de desastres
author:
- name: Raul E Ospina Villalobos
keywords:
- Estadística
- Información Geoespacial
- Geovisores
- Geoportal
- Gestión
abstract: DANE Colombia, Máster en ciencias de la información Geográfica, Especialista en Sistemas de Información Geográfica e Ingeniero Catastral y geodesta.
categories:
- Sesión 10. Inteligencia artificial, ciencia, tecnología e innovación
---

DANE Colombia, Máster en ciencias de la información Geográfica, Especialista en Sistemas de Información Geográfica e Ingeniero Catastral y geodesta.

Para el DANE como entidad responsable de las estadísticas oficiales en Colombia, y en cumplimiento de la ley de estadísticas donde se cita que estas deben propender por que estén disponibles, para que puedan ser utilizadas por parte de las entidades del Estado en los documentos de política pública, planes, programas y proyectos. Es importante impulsar el uso de las tecnologías de vanguardia para la producción de estas.  Es así como con el uso de las tecnologías geoespaciales se debe disponer información suficiente y de calidad en diversos campos, como en este caso en la gestión de riesgos de desastres. El uso de la información geoespacial para la gestión de riesgos de desastres es un tema ya abordado en diferentes instancias en naciones unidas se habla de que se debe facilitar el acceso de la información geoespacial de calidad para el tema de riesgos de desastres.  Igualmente, dentro del marco Sendai y el plan nacional de gestión de riesgos de desastres de Colombia se nombra la importancia de esta en diferentes instancias de la gestión del riesgo, es por esto por lo que se quiere mostrar el avance de como la información estadística y geoespacial es un elemento clave dentro del ciclo de la gestión de riesgos de desastres. Se comenzará con mostrar la relevancia de la implementación de los marcos globales de información geoespacial y el marco integrado de información estadística, para desarrollar herramientas geoespaciales que apoyen las etapas del proceso estadístico. después se hablará de como el uso de las herramientas geoespaciales ayudan a mejorar las estadísticas oficiales, finalizando con promover el uso de dicha información dentro de la gestión de Riesgos de desastres. Se quiere hacer énfasis en la importancia del uso de estadísticas oficiales dese el contexto geoespacial dentro de la gestión de riesgos de desastres no solo para la identificación de modelos de predicción sino en todas las etapas de esta importante labor.
