---
title: 'Predicción de marejada de tormenta en San Andrés y Providencia: integración de SIPSEM en estrategias de gestión de riesgo'
author:
- name: Claudia P. Urbano-Latorre
  affiliations:
  - PhD(c) en Ciencias del Mar, Centro de Investigaciones Oceanográficas e Hidrográficas del Caribe (CIOH) - DIMAR, Cartagena, Colombia
  corresponding: true
  email: curbano@dimar.mil.co
- name: Andrés F. Cartagena P
  affiliations:
  - Ingeniero Oceanográfico, Centro de Investigaciones Oceanográficas e Hidrográficas del Caribe (CIOH)- DIMAR, Cartagena, Colombia
- name: Wilmer Rey
  affiliations:
  - PhD en Ingeniera de Costas, Centro de Investigaciones Oceanográficas e Hidrográficas del Caribe (CIOH)- DIMAR, Cartagena, Colombia
keywords:
- Pronóstico
- Marejada de tormenta
- Ciclones tropicales
- San Andrés y Providencia
- Modelación numérica
abstract: La Dirección General Marítima (DIMAR) a través del Centro de Investigaciones Oceanográficas e Hidrográficas del Caribe (CIOH) ha desarrollado dentro del proyecto SIPSEM (Sistema Integrado de pronósticos
  para Seguridad Marítima) herramientas para la predicción del estado del tiempo marino a nivel nacional y local y su influencia en la navegación y las actividades marítimas, a fin de salvaguardar la vida
  humana en el mar y realizar operaciones seguras, para los tomadores de decisiones y la comunidad marítima.
categories:
- Sesión 3. Explorando las amenazas marino costeras
---

La Dirección General Marítima (DIMAR) a través del Centro de Investigaciones Oceanográficas e Hidrográficas del Caribe (CIOH) ha desarrollado dentro del proyecto SIPSEM (Sistema Integrado de pronósticos para Seguridad Marítima) herramientas para la predicción del estado del tiempo marino a nivel nacional y local y su influencia en la navegación y las actividades marítimas, a fin de salvaguardar la vida humana en el mar y realizar operaciones seguras, para los tomadores de decisiones y la comunidad marítima.

La integración de SIPSEM con el pronóstico de marejada de tormenta es crucial para proporcionar información que aporte a la gestión del riesgo, ya que permite anticipar y mitigar los impactos adversos de fenómenos climáticos extremos en las comunidades costeras, reduciendo la vulnerabilidad y mejorando la capacidad de respuesta ante desastres.

Un factor diferencial significativo en la generación de pronósticos es el alto nivel de detalle a nivel de las islas de San Andrés y Providencia, además del uso de la metodología de ensambles que permite combinar múltiples salidas de modelos numéricos, mejorando la precisión y reduciendo la incertidumbre en las predicciones climáticas a nivel regional y local, de variables como oleaje y sobreelevación del nivel del mar. Además, ha sido crítico comprender la tendencia de la rápida evolución de los huracanes para mejorar los pronósticos de marejada de tormenta. Los huracanes pueden intensificarse rápidamente debido a factores atmosféricos y oceánicos, como el aumento de la temperatura del mar y cambios en la estructura del viento. Esta intensificación puede resultar en marejadas de tormenta más severas, dando poco tiempo para que las autoridades y las comunidades costeras se preparen adecuadamente. Así, la capacidad de anticipar cambios rápidos en la intensidad y trayectoria de los huracanes es esencial para emitir alertas tempranas y tomar decisiones informadas que protejan a las poblaciones vulnerables.
