---
title: 'Conmemoración de desastres: dinámicas comunitarias y espacios conmemorativos El caso de la tormenta Xynthia en La Faute sur Mer, Francia'
author:
- name: Florence Lahournat
keywords:
- Memoria de desastres
- Memorialización
- Monumentos de desastres
- Comunicación de riesgos
- Recuperación comunitaria
abstract: Profesora asociada junior, Instituto de Investigación para la Prevención de Desastres, Universidad de Kioto, Uji, Japón,
categories:
- Sesión 17. Enfoques diferenciales de la GRD
---

Profesora asociada junior, Instituto de Investigación para la Prevención de Desastres, Universidad de Kioto, Uji, Japón,

[[lahournat.florence.3a@kyoto-u.ac.jp]{.underline}](mailto:lahournat.florence.3a@kyoto-u.ac.jp)

La tormenta Xynthia es una gran depresión meteorológica que afectó áreas del océano Atlántico y Europa antes de avanzar por la parte occidental de Francia el 27 y 28 de febrero de 2010, causando daños materiales y pérdidas de vidas importantes. La tormenta, los altos coeficientes de marea y la marea alta provocaron marejadas ciclónicas repentinas y severas, que provocaron la rotura de diques en varios lugares y graves inundaciones a lo largo de la costa atlántica. Este evento puso de relieve las vulnerabilidades en la preparación para desastres y generó preguntas sobre el uso de la tierra, así como sobre las medidas de protección costera. La Faute-sur-Mer fue una de las ciudades costeras más afectadas por la tormenta Xynthia, con 29 víctimas. Esta investigación explora la compleja dinámica de la conmemoración del desastre en La Faute-sur-Mer a raíz de la tormenta Xynthia. Parte de la comunidad local jugó un papel clave en la campaña para la conmemoración del desastre, incluido el establecimiento de un monumento conmemorativo permanente y un espacio público para honrar la memoria de las víctimas y conmemorar la gravedad del desastre. Basado en el trabajo de campo y las entrevistas realizadas a lo largo de 2022 y 2023, este artículo se centra en evaluar el proceso de conmemoración tal como se ha desarrollado en La Faute-sur-Mer. Al explorar las condiciones y circunstancias que dieron forma a la respuesta de la comunidad y las actividades de conmemoración, este estudio investiga el papel y el valor de los espacios conmemorativos en la curación de la comunidad, las tradiciones de la memoria y la recuperación y resiliencia a largo plazo. También aborda las tensiones que surgieron dentro de la comunidad durante este tiempo, centrándose en los desafíos de la memoria colectiva, la propiedad narrativa y las prácticas de conmemoración. En última instancia, este estudio tiene como objetivo contribuir a una mejor comprensión de las complejidades involucradas en la conmemoración de desastres y la gestión de las tensiones dentro de las comunidades que atraviesan procesos de conmemoración al brindar perspectivas matizadas sobre las interacciones entre la dinámica comunitaria, los métodos de conmemoración y las representaciones espaciales de desastres pasados.
