---
title: Sistema híbrido de monitoreo para la evaluación de efectos térmicos en vigas de puentes de concreto
author:
- name: José M. Benjumea
  affiliations:
  - Doctor en Ingeniería Civil y Ambiental, Profesor Asociado de la Universidad Industrial de Santander, Bucaramanga, Colombia.
- name: Pedro J. Cavadia
  affiliations:
  - Estudiante de Maestría en Ingeniería Civil de la Universidad Industrial de Santander, Bucaramanga, Colombia.
- name: Oscar J. Begambre
  affiliations:
  - Doctor en Ingeniería Civil, Profesor de la Universidad Industrial de Santander, Bucaramanga, Colombia.
- name: Edison Osorio
  affiliations:
  - Doctor en Ingeniería Eléctrica, Profesor de la Universidad Industrial de Santander, Bucaramanga, Colombia.
keywords:
- Cambio climático
- Temperatura del puente
- Perfil de temperatura
- Dron
- Monitoreo
abstract: '[[josbenro@uis.edu.co]{.underline}](mailto:josbenro@uis.edu.co)'
categories:
- Sesión 14. Inteligencia artificial, ciencia, tecnología e innovación
---

[[josbenro@uis.edu.co]{.underline}](mailto:josbenro@uis.edu.co)

La respuesta de los puentes de concreto bajo las variaciones estacionales y diarias de temperatura que sufren será más crítica debido al cambio climático. Esta preocupación plantea la necesidad de medir las temperaturas de los puentes para evaluar la adecuación de las directrices de diseño para las acciones térmicas, como las establecidas en el Código Colombiano de Diseño de Puentes, y para estimar las fuerzas y deformaciones térmicas. Este trabajo discute el desarrollo, implementación y resultados parciales de un sistema de monitoreo térmico que combina un dron con cámara térmica integrada y una estación meteorológica. El sistema se implementó en un modelo a escala real de losa-viga de concreto reforzado de 1,2 m de largo. La viga consiste en una losa AASHTO tipo I y el espesor de la losa es de 0-15 m. El modelo fue diseñado para representar una viga exterior de un puente y tenía muchos termopares incrustados en una sección transversal para medir la temperatura interna. Las fotos térmicas capturadas por el dron se procesaron para construir perfiles de temperatura externa en una cara de la viga. Estos datos se integraron con la radiación solar, la precipitación, la dirección y la velocidad del viento registradas con una estación meteorológica ubicada a metros del modelo. Debido a las limitaciones de accesibilidad al laboratorio, los datos se midieron durante 30 días de 6:30 a 4:00 p. m. cada 30 minutos. La presentación cubrirá la comparación entre los perfiles térmicos externos (basados en drones) e internos (basados en termopares) y su correlación cualitativa con los datos meteorológicos. Este paso es fundamental antes de pasar a la segunda fase del desarrollo, en la que se integrará la inteligencia artificial para acelerar la predicción.
