---
title: Villa B un escenario de impactos socio-ambientales tras las inundaciones en Sucre-Sucre 2010.
author:
- name: Lila Y. Correa Cazado
- name: Juan D. Alvarado Barcinilla
keywords:
- Impactos socio-ambientales
- cultura anfibia
- Practicas resilientes
- inundaciones
abstract: Universidad del Atlántico, estudiante de pregrado en sociología, Barranquilla, Colombia
categories:
- Sesión 17. Enfoques diferenciales de la GRD
---

Universidad del Atlántico, estudiante de pregrado en sociología, Barranquilla, Colombia

[[lycorrea@mail.uniatlantico.edu.co]{.underline}](mailto:lycorrea@mail.uniatlantico.edu.co)

La ocurrencia de las inundaciones tiene presencia a nivel mundial, empero los países de la zona ecuatorial por gozar de las riquezas ecosistémica de ríos, lagos, humedales, mares tiende a recibir los impactos del aumento de las precipitaciones. El territorio colombiano en el año 2010-2011 sufrió el aumento de las precipitaciones como efecto directo de la denominada temporada invernal, según Sánchez (2014) el fenómeno de la Niña ha sido unos de los desastres naturales con mayores secuelas en la historia de la nación, está provocó cuantiosas pérdidas sociales y económicas. En ese orden de ideas las inundaciones son un evento recurrente en nuestra nación. La región caribe tiene en su espacio geográfico la denominada subregión de la Mojana, la anterior es un territorio compuesto por cuartos regiones: Antioquia, Bolívar, Córdoba y Sucre, que se caracteriza por concentrar una compleja red hídrica de caños, humedales y los ríos más importantes Magdalena, Cauca y San Jorge. En este espacio se genera de manera cíclica dos etapas: el fuerte verano con sus efectos directos las sequías y el invierno con el aumento de las precipitaciones y posteriores inundaciones. El objetivo central de la investigación fue determinar las acciones que movilizó la población de Villa B, en Sucre-Sucre para enfrentar las inundaciones del 2010, en los acercamientos previos a través de observaciones no participantes y observaciones etnográfica  se hallaron las siguientes prácticas que emprenden la comunidad de Villa-B y en gran medida la cabera municipal de Sucre: la creación de tambos estas estructura de madera seca, permite la circulación dentro de la vivienda y la protección de enseres en lugares altos de la vivienda, la creación de canoas de maderas y valsas con materiales reciclables para el transporte interno en el barrio y la cabecera.
