---
title: Impactos económicos de los desastres complejos que afectan a los puertos gemelos de Los Ángeles y Long Beach
author:
- name: Adam Rose
- name: Noah Miller
- name: Zhenhua Chen
- name: Fred Roberts
- name: Andrew Tucci
- name: Latha Vijayagopal
keywords:
- desastres complejos
- puertos marítimos
- eventos complejos
abstract: Adam Rose, Noah Miller, Zhenhua Chen, Fred Roberts, Andrew Tucci, Latha Vijayagopal
categories:
- Sesión 22. Preparación para una respuesta a múltiples riesgos
---

Adam Rose, Noah Miller, Zhenhua Chen, Fred Roberts, Andrew Tucci, Latha Vijayagopal

Las perturbaciones económicas en los puertos marítimos son cada vez más frecuentes por razones directas como el cambio climático, que puede manifestarse a corto plazo a través de huracanes más intensos y mareas de tempestad más fuertes, y a través del aumento del nivel del mar a largo plazo. Otra es la posibilidad de terrorismo en forma de agentes químicos, biológicos, radiológicos o nucleares (CBRN) que se insertan en los contenedores de transporte marítimo y que pueden causar una contaminación generalizada de la carga y las instalaciones circundantes, así como la muerte y lesiones al personal portuario. Otra razón es la continuación de la historia de disturbios laborales, que esporádicamente da lugar a cierres o desaceleraciones de los puertos. Además de las perturbaciones directamente en el lugar, los eventos fuera del lugar pueden tener consecuencias desastrosas. Por ejemplo, los incendios forestales pueden causar cortes de energía, tanto planificados como no planificados. Otra categoría de fuentes indirectas son los acontecimientos sociopolíticos, como las recientes tensiones en Oriente Medio, que han provocado importantes desvíos de rutas de buques que aumentan la congestión en algunos puertos, aumentando así significativamente los costos de transporte y haciendo que los accidentes marítimos graves sean más probables. Los puertos marítimos son infraestructuras fundamentales para la actividad económica, como parte del sistema marino (marítimo) y, de manera más amplia, como parte de los sistemas de comercio nacional e internacional a través de su papel como nodos en redes de transporte complejas (citas). Por lo tanto, las interrupciones en su funcionamiento tendrán un efecto dominó en las economías regionales, nacionales e internacionales. Simulamos los impactos económicos regionales y nacionales de tres interrupciones superpuestas y en cascada para los puertos gemelos de Los Ángeles y Long Beach, California, el complejo portuario de contenedores más activo de los Estados Unidos: 1) Huelga laboral, 2) Pérdida de energía eléctrica debido a incendios forestales y 3) Incidente terrorista que afecta a los contenedores de envío. El análisis se realizará aplicando el marco de análisis de consecuencias económicas (ECA) (Rose 2015; Rose et al. 2017), que es un proceso analítico y empírico integral de varios pasos desarrollado en el Centro de Riesgo y Análisis Económico de Amenazas de la Universidad del Sur de California. El enfoque de modelado macroeconómico es la aplicación de un modelo de equilibrio general computable (CGE) multirregional conocido como TERM (Horridge et al. 2017), que es capaz de estimar los impactos en toda la economía de las disrupciones individuales y complejas que funcionan a través de las cadenas de suministro. Este modelo se ha utilizado con éxito en análisis anteriores de disrupciones económicas en general (p. ej., Wittwer, 2022) y del sistema de transporte marítimo en particular (ver p. ej., Wei et al. 2020, 2022; Chen et al. 2024). Este documento avanza la literatura de varias maneras. Es el primer estudio que examina una disrupción compleja en un puerto marítimo que consta de tres eventos superpuestos y en cascada. Descompone los resultados según los factores causales y deriva una ecuación de regresión en forma reducida que puede utilizarse para realizar estimaciones rápidas y para comprobar la sensibilidad de los resultados a los supuestos básicos y la influencia relativa de los factores que impulsan los impactos.
