---
title: 'Revelando la Dinámica del Riesgo con Cadenas de Impacto: una sesión práctica sobre análisis participativo de riesgos'
author:
- name: Federica Romagnoli
  affiliations:
  - Head of Center \_ Center for Global Mountain Safeguard Research. United Nations University- Institute for Environment and Human Security (UNU-EHS), Germany, Stefan.Schneiderbauer@eurac.edu
keywords:
- Cadenas de impacto
- análisis del riesgo
- metodologías
abstract: Si bien se reconoce ampliamente que los riesgos resultan de la interacción dinámica de tres elementos fundamentales (amenazas, exposición y vulnerabilidad), las metodologías de análisis o evaluación
  de riesgos suelen caracterizarse por un enfoque compartimentado que dificulta la comprensión de la dinámica del riesgo y, en consecuencia, limita la eficacia de las opciones de adaptación. En esta sesión,
  presentaremos y guiaremos a los participantes en la implementación de Cadenas de Impacto, una herramienta analítica capaz de desentrañar las interacciones entre múltiples componentes del riesgo, describir
  los factores clave de vulnerabilidad y simplificar las diferentes relaciones causales que determinan las vías de riesgo específicas. Además de ofrecer un nuevo enfoque para el análisis de riesgos, la
  metodología de Cadenas de Impacto promueve una comprensión integral de la dinámica del riesgo compartida por múltiples actores. Esta metodología cuenta con un fuerte componente participativo, que permite
  delinear una imagen de los riesgos específicos de un contexto dado, a la vez que permite a los actores locales y expertos reflexionar e identificar vulnerabilidades contextuales específicas. Los participantes
  de esta sesión adquirirán una comprensión profunda del marco teórico que sustenta la metodología, además de la oportunidad de aplicarlo en un ejercicio grupal. Esta experiencia práctica les brindará habilidades
  prácticas para mejorar sus estrategias de análisis de riesgos y adaptación.
categories:
- Sesiones Especiales
---

**Sobre la sesión:** Si bien se reconoce ampliamente que los riesgos resultan de la interacción dinámica de tres elementos fundamentales (amenazas, exposición y vulnerabilidad), las metodologías de análisis o evaluación de riesgos suelen caracterizarse por un enfoque compartimentado que dificulta la comprensión de la dinámica del riesgo y, en consecuencia, limita la eficacia de las opciones de adaptación. En esta sesión, presentaremos y guiaremos a los participantes en la implementación de Cadenas de Impacto, una herramienta analítica capaz de desentrañar las interacciones entre múltiples componentes del riesgo, describir los factores clave de vulnerabilidad y simplificar las diferentes relaciones causales que determinan las vías de riesgo específicas. Además de ofrecer un nuevo enfoque para el análisis de riesgos, la metodología de Cadenas de Impacto promueve una comprensión integral de la dinámica del riesgo compartida por múltiples actores. Esta metodología cuenta con un fuerte componente participativo, que permite delinear una imagen de los riesgos específicos de un contexto dado, a la vez que permite a los actores locales y expertos reflexionar e identificar vulnerabilidades contextuales específicas. Los participantes de esta sesión adquirirán una comprensión profunda del marco teórico que sustenta la metodología, además de la oportunidad de aplicarlo en un ejercicio grupal. Esta experiencia práctica les brindará habilidades prácticas para mejorar sus estrategias de análisis de riesgos y adaptación.

**Objetivos**: i) explicar los conceptos de la metodología de la cadena de impacto, ii) experimentar la implementación de la metodología. La idea de la sesión es ampliar los conocimientos de los participantes sobre las metodologías de análisis de riesgos y brindarles la oportunidad de aplicar los conocimientos adquiridos durante una actividad participativa. A través de esta actividad interactiva, también buscamos ofrecer un espacio colaborativo para estimular el aprendizaje mutuo y el intercambio de conocimientos entre los participantes. Asimismo, esperamos se genere networking con expertos regionales e internacionales que trabajan en análisis de riesgos.

**Justificación**: En un mundo cada vez más globalizado, los desafíos sociales interactúan con condiciones climáticas cambiantes, lo que genera riesgos en constante evolución para las sociedades. La ciencia del riesgo reconoce progresivamente las complejidades y los desafíos multifacéticos inherentes al análisis de riesgos. Sin embargo, las metodologías tradicionales de análisis de riesgos a menudo no ofrecen un análisis exhaustivo, centrándose con frecuencia en elementos de riesgo individuales. Aquí se desarrolla una metodología que aborda las limitaciones de los marcos convencionales de evaluación de desastres y análisis de riesgos. Nuestro enfoque ofrece una representación sistemática e integral de los componentes del riesgo, basada en el conocimiento contextual y la comprensión de la dinámica del riesgo, desarrollada en colaboración con actores locales y expertos. La sesión se alinea con la Prioridad 1 del Marco de Sendai al proporcionar una metodología que capta mejor las interacciones entre los componentes del riesgo, reflejando la naturaleza dinámica y compleja del mismo. Con un enfoque participativo, esta sesión permite a los participantes adquirir experiencia en la implementación de la metodología. Este formato interactivo distingue a nuestra sesión de otras sesiones temáticas planificadas en la conferencia, fomentando el intercambio entre los participantes y fortaleciendo sus habilidades prácticas.
