---
title: Digitalización del mapeo participativo del riesgo basado en papel con la herramienta Sketch Map
author:
- name: Anne Schauss
  affiliations:
  - Instituto de Heidelberg para la Tecnología de la Geoinformación (HeiGIT), investigadora asociada
- name: Eduard Giovanni Ruiz Morales
  affiliations:
  - Cruz Roja Colombiana, Gestor Nacional de Conocimiento del Riesgo
- name: Maria Jimena Henao Salgado
  affiliations:
  - Universidad Nacional de Colombia sede Manizales, investigador
- name: Natalia Cardona Gómez
  affiliations:
  - Universidad Nacional de Colombia
keywords:
- Riesgo de desastres
- cartografía participativa
- resiliencia
- digitalización
- conocimiento local
abstract: 'Se empleó Sketch Map Tool, una tecnología de código abierto diseñada para cerrar brechas entre métodos tradicionales de mapeo a mano y la creciente demanda de análisis y almacenamiento de datos.
  En la sesión los participantes conocieron dos componentes de esta herramienta: la recolección analógica de datos mediante mapas dibujados a mano y una aplicación web que permite la digitalización automática,
  el análisis de la calidad de datos en OpenStreetMap (OSM) y la integración de imágenes satelitales. Mediante demostraciones y un ejercicio práctico en grupo, los asistentes adquirieron experiencia directa
  en el uso del Sketch Map Tool, explorando sus aplicaciones en la gestión integrada del riesgo de desastres.'
categories:
- Sesiones Especiales
---

**Sobre la sesión:** Se empleó Sketch Map Tool, una tecnología de código abierto diseñada para cerrar brechas entre métodos tradicionales de mapeo a mano y la creciente demanda de análisis y almacenamiento de datos. En la sesión los participantes conocieron dos componentes de esta herramienta: la recolección analógica de datos mediante mapas dibujados a mano y una aplicación web que permite la digitalización automática, el análisis de la calidad de datos en OpenStreetMap (OSM) y la integración de imágenes satelitales. Mediante demostraciones y un ejercicio práctico en grupo, los asistentes adquirieron experiencia directa en el uso del Sketch Map Tool, explorando sus aplicaciones en la gestión integrada del riesgo de desastres.

**Objetivos: 1)** Familiarizarse con el Sketch Map Tool y sus aplicaciones en la gestión del riesgo de desastres mediante enfoques participativos. 2) Desarrollar conocimientos y habilidades para utilizar el Sketch Map Tool en su trabajo profesional, promoviendo la participación comunitaria y una toma de decisiones informada en la gestión del riesgo de desastres. 3) Explorar su uso en la cartografía de percepciones del riesgo y la aplicación de enfoques participativos en investigaciones forenses de desastres. 4) Aplicar la herramienta en la identificación de preferencias individuales y grupales para evaluaciones comunitarias del riesgo de desastres y estrategias de reducción del riesgo. 5) Integrar el Sketch Map Tool en enfoques de adaptación basada en ecosistemas, fortaleciendo la resiliencia comunitaria ante amenazas ambientales.

**Justificación**: La evaluación del riesgo de desastres y la planificación de estrategias requieren datos sobre amenazas, vulnerabilidades y capacidades, a menudo ausentes en comunidades remotas y vulnerables. Esta falta de información espacial local limita su capacidad para fortalecer la resiliencia. No obstante, las comunidades poseen conocimiento local valioso sobre el riesgo, esencial para su comprensión. Las investigaciones forenses de desastres (FORIN) demandan mayor participación social para analizar cómo factores dinámicos convierten las causas raíz en condiciones de inseguridad. La cartografía participativa, clave en enfoques de Investigación Acción Participativa en Reducción del Riesgo de Desastres, facilita la recolección y uso de datos espaciales locales para la acción colectiva. Métodos en papel como mapas a mano alzada o a escala, de bajo costo y accesibles, son útiles para comunidades con escasa alfabetización digital y permiten una mejor comprensión de los mapas. Sin embargo, digitalizar estos contenidos es laborioso y propenso a errores, lo que puede limitar su uso para la incidencia externa o análisis cuantitativo. El Sketch Map Tool permitió aprovechar los beneficios de los mapas en papel dentro de la cartografía participativa, al proporcionar eficiencia en el tiempo y garantizar el uso sostenible de la información a través de su digitalización. A diferencia de otras sesiones temáticas ya programadas, esta sesión incluyó una experiencia de aprendizaje exploratoria sobre las aplicaciones potenciales del Sketch Map Tool en la gestión integrada del riesgo de desastres mediante tecnologías de mapeo participativo.
