---
title: Estudio sobre el mecanismo de interferencia entre el riesgo integrado de múltiples peligros, la economía y la población basado en datos de múltiples fuentes
author:
- name: Yun Chen
- name: Qiushan Li
keywords:
- Superposición de riesgos de peligros múltiples
- Grupos económicamente desfavorecidos
- Distribución espacial
- Mecanismo de interferencia
abstract: La Universidad Politécnica de Hong Kong-Instituto para la Gestión de Desastres y la Reconstrucción (IDMR), Universidad de Sichuan, Chengdu 610207, China
categories:
- Sesión 18. Aseguramiento y protección financiera para la GRD
---

La Universidad Politécnica de Hong Kong-Instituto para la Gestión de Desastres y la Reconstrucción (IDMR), Universidad de Sichuan, Chengdu 610207, China

En el mundo actual, la ocurrencia frecuente de desastres naturales y grupos de desastres exacerba el escenario general de desastres, mientras que los efectos combinados de los riesgos multi-amenaza plantean amenazas significativas para el desarrollo socioeconómico y demográfico. En el entorno de múltiples peligros, el desarrollo de estrategias integradas de prevención de riesgos debe considerar los mecanismos de interferencia de los desastres, la economía y la población. Este estudio, basado en las características espaciales del riesgo combinado, la riqueza y la distribución de la población de cuatro tipos de amenazas naturales, investiga los mecanismos de interferencia que vinculan los riesgos multi-amenaza, las economías y las poblaciones en la provincia de Sichuan, China, y analiza los desafíos de los impactos de los desastres en el desarrollo socioeconómico y demográfico. Utilizando datos estadísticos tradicionales, teledetección y otros conjuntos de datos de información espacial relacionados con la evaluación de riesgos multi-amenaza, este estudio emplea una combinación de análisis jerárquicos y espaciales para superponer distribuciones integradas de riesgo de desastres naturales, población y PIB. Además, introduce el concepto de \"sesgo de exposición a la pobreza relativa (RPEB)\" para evaluar la vulnerabilidad relativa de los grupos económicamente desfavorecidos que enfrentan riesgos multi-amenaza en diferentes ciudades y regiones de la provincia de Sichuan. Los hallazgos revelan que la superposición de riesgos de múltiples amenazas explica la distribución espacial de áreas integrales de alto riesgo en la provincia. A nivel provincial, las áreas de alto riesgo de múltiples amenazas muestran una correlación negativa con el estatus socioeconómico y la densidad de población, mientras que muestran una tendencia hacia la correlación positiva a escala municipal. El RPEB explica además la relación entrelazada entre las amenazas socioeconómicas, demográficas y naturales combinadas, y que la vulnerabilidad de los grupos económicamente desfavorecidos a las amenazas integradas de alto riesgo demuestra una relación compleja y no lineal que no se correlaciona uniformemente con las condiciones económicas regionales. Este estudio destaca los mecanismos de interferencia que vinculan la superposición de riesgos multi-amenaza con factores socioeconómicos y demográficos, y ofrece información valiosa para la formulación de estrategias integradas de preparación para amenazas múltiples adaptadas a diversas regiones.
