---
title: 'Desentrañando las complejas interacciones entre los componentes de riesgo a través de la metodología de la cadena de impacto: una aplicación al estudio de caso de la tormenta Vaia'
author:
- name: Federica Romagnoli
  affiliations:
  - Universidad de las Naciones Unidas-Instituto para el Medio Ambiente y la Seguridad Humana (UNU-EHS), Alemania
  corresponding: true
  email: federica.romagnoli@eurac.edu
- name: Silvia Cocuccioni
  affiliations:
  - Departamento de Geografía, Universidad del Estado Libre, Sudáfrica
- name: Liz Jessica Olaya Calderòn
  affiliations:
  - Universidad de las Naciones Unidas-Instituto para el Medio Ambiente y la Seguridad Humana (UNU-EHS), Alemania
- name: Massimiliano Pittore
  affiliations:
  - Universidad de las Naciones Unidas-Instituto para el Medio Ambiente y la Seguridad Humana (UNU-EHS), Alemania
- name: Stefan Schneiderbauer
  affiliations:
  - Universidad de las Naciones Unidas-Instituto para el Medio Ambiente y la Seguridad Humana (UNU-EHS), Alemania
keywords:
- Análisis de múltiples riesgos
- Cadenas de impacto
- Eventos meteorológicos extremos
- Riesgos relacionados con el clima
abstract: Las amenazas y riesgos relacionados con el clima son sistémicos y multifacéticos, y se vuelven cada vez más complejos en contextos de múltiples riesgos. A medida que el cambio climático intensifica
  los fenómenos meteorológicos extremos, se espera que los múltiples riesgos y amenazas se vuelvan más frecuentes. Al mismo tiempo, las variables sociales y humanas influyen en la vulnerabilidad y la exposición,
  afectando la capacidad de los sistemas socioambientales para hacer frente a los riesgos futuros relacionados con el clima. La comunidad científica de riesgos reconoce la naturaleza interconectada del
  riesgo, pero las metodologías actuales para el análisis y la evaluación de riesgos no logran abordar estas complejidades. Para avanzar en la ciencia de riesgos, EURAC Research, en colaboración con otros
  socios, ha desarrollado un marco conceptual llamado Cadenas de Impacto (IC). Este marco representa de manera sistemática y completa las interacciones entre los componentes de riesgo, como los peligros,
  la exposición y la vulnerabilidad. Permite la identificación de vías de riesgo específicas dentro de contextos geográficos y temporales determinados.
categories:
- Sesión 7. Identificación de riesgos, evaluación de riesgos y evaluación de riesgos sistémicos y complejos
---

Las amenazas y riesgos relacionados con el clima son sistémicos y multifacéticos, y se vuelven cada vez más complejos en contextos de múltiples riesgos. A medida que el cambio climático intensifica los fenómenos meteorológicos extremos, se espera que los múltiples riesgos y amenazas se vuelvan más frecuentes. Al mismo tiempo, las variables sociales y humanas influyen en la vulnerabilidad y la exposición, afectando la capacidad de los sistemas socioambientales para hacer frente a los riesgos futuros relacionados con el clima. La comunidad científica de riesgos reconoce la naturaleza interconectada del riesgo, pero las metodologías actuales para el análisis y la evaluación de riesgos no logran abordar estas complejidades. Para avanzar en la ciencia de riesgos, EURAC Research, en colaboración con otros socios, ha desarrollado un marco conceptual llamado Cadenas de Impacto (IC). Este marco representa de manera sistemática y completa las interacciones entre los componentes de riesgo, como los peligros, la exposición y la vulnerabilidad. Permite la identificación de vías de riesgo específicas dentro de contextos geográficos y temporales determinados.

La versatilidad de las IC permite su uso en el análisis de riesgos actuales y futuros a través de diversas metodologías, incluidos procesos participativos, simulaciones de desarrollo de escenarios y análisis retrospectivo de desastres (por ejemplo, análisis forense). En el marco del proyecto "PARATUS" de Horizonte Europa de la UE, se aplicó la IC para analizar eventos de múltiples riesgos. Esta contribución presenta la base teórica de la metodología y su aplicación práctica en el examen de la tormenta de viento Vaia. La tormenta de viento Vaia, que azotó Italia en 2018, provocó lluvias de alta intensidad y ráfagas de viento intensas. La aplicación de la IC demostró su potencial para captar la diversidad de componentes de riesgo, vulnerabilidades y factores de riesgo, destacando la importancia de las conexiones entre elementos físicos y sociales. Este estudio subraya la necesidad de metodologías avanzadas como la IC para comprender y gestionar la dinámica compleja de los riesgos relacionados con el clima. Al proporcionar un análisis integral de eventos de múltiples amenazas, la IC puede informar mejores estrategias de gestión de riesgos y adaptación, mejorando la resiliencia de los sistemas socioambientales frente a los crecientes desafíos climáticos.
