---
title: 'Planificación Territorial, Gestión de Políticas Públicas y Agenda Urbana: resiliencia de las ciudades y sus territorios en el contexto del cambio climático y las vulnerabilidades socioambientales'
author:
- name: Maria Galleno de S
- name: Oliveira
abstract: Centro de Estudos de Regulação e Governança -- UNESP-Campus de Franca/SP-Brasil
categories:
- Sesión 19. Participación comunitaria y ONGs
---

Centro de Estudos de Regulação e Governança -- UNESP-Campus de Franca/SP-Brasil

\*Autora de contacto: Maria Galleno de S, Oliveira, maria.galeno@unesp.br

La investigación propone analizar e identificar los desafíos, estrategias y acciones para mitigar y adaptar el territorio urbano para enfrentar el cambio climático y el creciente aumento de las vulnerabilidades socioambientales resultantes de los eventos climáticos extremos. Las crisis climáticas acentúan las desigualdades, dado que los grupos más vulnerables (niños, mujeres, ancianos, homosexuales, negros, mestizos y personas que viven en asentamientos informales) están más expuestos a los riesgos derivados de los eventos climáticos extremos. Cada vez más personas viven en zonas marginales carentes de infraestructura y servicios esenciales, condiciones que se agravan aún más con el cambio climático, lo que requiere el desarrollo de políticas públicas, infraestructura, gestión y planificación territorial que incluyan asentamientos informales adaptados al cambio climático. Desde una perspectiva interdisciplinaria, basada en la teoría de la tradición del conflicto (Marx, Engels y Weber), la teoría de la sociedad del riesgo (Ulrich Beck), el derecho a la ciudad (Lefebvre y Harvey), el uso del espacio y del territorio (Milton Santos, Hall, Choay y Rodrigues), en la teoría del urbanismo centrado en la decisión (Daviddoff y Reiner) y en las teorías de políticas públicas (Abruccio, Perreira, Keinart y Lubell), se pretende proporcionar un enfoque metodológico plural, basado en investigaciones bibliográficas, documentales, de campo y de caso, con el objetivo de establecer parámetros y ofrecer respuestas que puedan auxiliar y mejorar los instrumentos de política pública para la planificación urbana territorial -- especialmente para los asentamientos informales en el estado de São Paulo -- para un futuro adaptado al cambio climático y servir como insumo para identificar áreas de vulnerabilidad y para desarrollar un plan participativo de gestión de riesgos para las sociedades locales, promoviendo la inclusión y participación de las poblaciones vulnerables y posibilitando el fortalecimiento de estos actores en la gestión y planificación territorial.
