---
title: Evaluación del riesgo sísmico para la ciudad de Santiago de Cali, Colombia
author:
- name: Nathalie García-Millán
  affiliations:
  - Secretaría de Gestión del Riesgo de Emergencias y Desastres, Santiago de Cali, Colombia
  corresponding: true
  email: nathalie.garcia@cali.gov.co
- name: Andrés Prieto
  affiliations:
  - Departamento Administrativo de Planeación, Santiago de Cali, Colombia
- name: Catalina Yepes-Estrada
  affiliations:
  - Fundación GEM (Global Earthquake Model) , Pavia, Italia
- name: Alejandro Calderón Ana Beatriz Acevedo
  affiliations:
  - Universidad EAFIT, Medellín, Colombia
keywords:
- Riesgo sísmico
- Reducción del riesgo sísmico
- Escenarios sísmicos
abstract: Dentro de la gestión integral del riesgo de desastres el conocimiento del riesgo sísmico (identificación de sus componentes, estimación y comunicación del riesgo) es fundamental para desarrollar
  estrategias de prevención, mitigación y respuesta ante terremotos. Una efectiva evaluación del riesgo requiere la interacción de modeladores del riesgo y tomadores de decisión, de modo que los resultados
  se ajusten a las necesidades del territorio y puedan usarse en la definición de estrategias para la preparación, ejecución de la respuesta y la recuperación ante terremotos. La evaluación del riesgo sísmico
  requiere la colaboración de un equipo interdisciplinario que comprenda la geología y sismicidad local, las características y el número de las edificaciones existentes y los habitantes que las ocupan,
  y la vulnerabilidad sísmica de los edificios según la práctica constructiva. Los resultados de esta evaluación deben ser comunicados y socializados con los diferentes actores de la gestión del riesgo
  de desastres, entre ellos con las autoridades pertinentes.
categories:
- Sesión 6. Comunicación y educación en DRM
---

Dentro de la gestión integral del riesgo de desastres el conocimiento del riesgo sísmico (identificación de sus componentes, estimación y comunicación del riesgo) es fundamental para desarrollar estrategias de prevención, mitigación y respuesta ante terremotos. Una efectiva evaluación del riesgo requiere la interacción de modeladores del riesgo y tomadores de decisión, de modo que los resultados se ajusten a las necesidades del territorio y puedan usarse en la definición de estrategias para la preparación, ejecución de la respuesta y la recuperación ante terremotos. La evaluación del riesgo sísmico requiere la colaboración de un equipo interdisciplinario que comprenda la geología y sismicidad local, las características y el número de las edificaciones existentes y los habitantes que las ocupan, y la vulnerabilidad sísmica de los edificios según la práctica constructiva. Los resultados de esta evaluación deben ser comunicados y socializados con los diferentes actores de la gestión del riesgo de desastres, entre ellos con las autoridades pertinentes.

Este estudio presenta los resultados de la evaluación del riesgo sísmico para la ciudad de Santiago de Cali, Colombia, realizado como parte del proyecto TREQ (Training and Communication for Earthquake Risk Assessment, [[github.com/gem/treq-riesgo-urbano/tree/main/Cali]{.underline}](https://github.com/gem/treq-riesgo-urbano/tree/main/Cali)) en colaboración con los gestores de gestión del riesgo de la ciudad. Los resultados incluyen perfiles de riesgo que destacan áreas vulnerables del municipio e información necesaria para la definición de esquemas de protección financiera; así como posibles escenarios de respuesta ante diferentes tipos de terremotos. La información de los perfiles se definió de manera conjunta entre los modeladores del riesgo y las autoridades locales, facilitando así su comprensión y uso en la toma de decisiones. Esta información se ha compartido con las autoridades locales y otros actores relevantes, permitiendo identificar áreas de mejora y entender el impacto de políticas específicas en la reducción del riesgo sísmico en la ciudad.
