---
title: Medición y comprensión del conocimiento ambiental en la conservación de los servicios ecosistémicos
author:
- name: Dra. Tlou D. Raphela
keywords:
- Conocimiento ecológico
- servicios ecosistémicos
- comunidades rurales
- municipio de Thulamela
abstract: Universidad del Estado Libre, Centro de Educación y Capacitación en Gestión de Desastres para África, Bloemfontein, Sudáfrica, 0193
categories:
- Sesión 20. Capacidad adaptativa y reducción de la vulnerabilidad ante riesgos ambientales y climáticos
---

Universidad del Estado Libre, Centro de Educación y Capacitación en Gestión de Desastres para África, Bloemfontein, Sudáfrica, 0193

[[madeizen@gmail.com]{.underline}](mailto:madeizen@gmail.com); [[RaphelaTD@ufs.ac.za]{.underline}](mailto:RaphelaTD@ufs.ac.za)

Los servicios ecosistémicos se encuentran entre los servicios más críticos que sustentan muchos medios de vida; estos servicios regulan el entorno natural de las personas, apoyan los procesos naturales y proporcionan recursos y valores culturales. Como tal, a lo largo de los años, se desarrollaron relaciones sólidas entre las personas y la naturaleza. Posteriormente, las personas desarrollaron conocimientos sobre su entorno natural y establecieron tradiciones para mantener y conservar los servicios ecosistémicos. En este contexto, debido a que las estrategias de conservación estatales formales son inadecuadas o no se aplican en las comunidades rurales, este estudio tiene como objetivo comprender la razón detrás del declive en la conservación de los servicios ecosistémicos tradicionales. El estudio es puramente cualitativo y los datos recopilados a través de un enfoque de revisión sistemática de la literatura. Se identificaron estudios relevantes en inglés de 2000 a 2022 en el contexto africano a partir de Web of Science, EBSCO y Google Scholar. El estudio aplicó un análisis de contenido deductivo e inductivo de la literatura identificada utilizando el software NVivo. El estudio comenzó con el enfoque deductivo para abordar la pregunta de investigación e incorporó elementos inductivos para capturar los hallazgos. El estudio indicó que las prácticas de conocimiento tradicional para la conservación y gestión de los servicios ecosistémicos en todo el municipio eran tótems, predicciones astronómicas y climáticas, rituales, reglas, creencias, tabúes y mitos, y conocimiento tradicional. En segundo lugar, la conciencia, el valor y el uso del conocimiento tradicional se han deteriorado como consecuencia de la influencia cultural occidental. Además, los hallazgos del estudio revelaron diferencias en la conciencia, el valor y el uso del conocimiento tradicional, lo que demuestra que las personas más jóvenes perciben el conocimiento tradicional como arcaico. El estudio indicó que las contribuciones del conocimiento tradicional a la conservación y gestión de los servicios ecosistémicos en todo el municipio se redujeron debido a la disminución del uso, el valor y la conciencia de la tradición.
