---
title: Estimación del impacto económico de la erupción del volcán Taal mediante el consumo de electricidad
author:
- name: Ma. Flordeliza P. Del Castillo
  affiliations:
  - Departamento de Informática Social, Escuela de Posgrado en Informática, Universidad de Kioto, Japón
- name: Toshio Fujimi y Hirokazu Tatano
  affiliations:
  - Geomática para el Medio Ambiente y el Desarrollo, Observatorio de Manila, Universidad Ateneo de Manila, Ciudad Quezón, Filipinas
keywords:
- SNPP VIIRS DNB
- Filipinas
- Regresión
- Teledetección
- Pérdidas y daños por desastres
abstract: '[[del.pajarillo.83r@st.kyoto-u.ac.jp]{.underline}](mailto:del.pajarillo.83r@st.kyoto-u.ac.jp)'
categories:
- Sesión 18. Aseguramiento y protección financiera para la GRD
---

[[del.pajarillo.83r@st.kyoto-u.ac.jp]{.underline}](mailto:del.pajarillo.83r@st.kyoto-u.ac.jp)

La estimación de los impactos económicos es fundamental para proporcionar un apoyo financiero adecuado a las unidades afectadas. En concreto, la información sobre la distribución espacial y temporal de los impactos es fundamental para la distribución proporcionada y oportuna del apoyo. Sin embargo, las estimaciones del impacto económico a menudo carecen de dimensión espacial, lo que provoca un desajuste entre la asignación de recursos y la dimensión temporal, lo que provoca retrasos. Este documento utilizó datos de consumo de electricidad (CE) y luz nocturna para estimar y mapear los impactos económicos de la erupción del volcán Taal en Filipinas el 12 de enero de 2020. Se generó un modelo de CE a partir de los datos de consumo de electricidad previos a la erupción y luego se utilizó para predecir un CE contrafactual a partir del cual se calculó la pérdida de CE. La pérdida de CE se convirtió a valores de PIB utilizando un modelo de regresión que estima el PIB trimestral nacional en CE. Luego se calcularon los impactos económicos utilizando tres técnicas de diferenciación que varían en valores de referencia. Se mapearon los impactos por municipio para identificar los municipios más afectados. Los resultados estimaron que los impactos económicos totales al 30 de enero de 2020 fueron de 9.2 mil millones de PHP. Los resultados indican que la mayor parte de la pérdida de CE se produjo durante las primeras dos semanas, y se estabilizó en la tercera semana. Los municipios más afectados fueron Sta. Teresita, Talisay, Laurel, Agoncillo, San Nicolás, Taal, Lemery y Balete. En general, la CE y la NTL pueden ser una medida alternativa útil para estimar y mapear los impactos económicos de las erupciones volcánicas.
