---
title: 'Concientización sobre el empoderamiento de las mujeres y el papel del teatro: un estudio en un pueblo de Bengala Occidental, India'
author:
- name: Debkalpa BasuDas
keywords:
- Teatro; Empoderamiento de la mujer
- Concientización
- Violencia contra la mujer (VCM)
abstract: Investigadora doctoral, Centro de Investigación de Estudios de la Mujer, Universidad de Calcuta, Kolkata, India
categories:
- Sesión 17. Enfoques diferenciales de la GRD
---

Investigadora doctoral, Centro de Investigación de Estudios de la Mujer, Universidad de Calcuta, Kolkata, India

[[debkalpabd@gmail.com]{.underline}](mailto:debkalpabd@gmail.com)

Facilitar el proceso de empoderamiento de las mujeres es muy importante para permitirles mejorar su autoestima y permitirles defender la igualdad y ayudar a otras mujeres a hablar. El tema está estrechamente relacionado con la cuestión de los derechos humanos y el desarrollo de un país, y la sensibilización sobre el empoderamiento de las mujeres y la violencia contra las mujeres es esencial para el desarrollo social. El presente estudio explora la eficacia del teatro como medio para sensibilizar a las masas sobre cuestiones de género muy debatidas y cruciales, la violencia contra las mujeres y el empoderamiento de las mujeres, así como la eficacia del teatro como medio de comunicación. Realizamos una encuesta de campo en la aldea de Bishnuvati, Birbhum, Bengala Occidental, con 50 encuestadas para evaluar el nivel de concienciación sobre la violencia contra las mujeres (VAW) y se representó una obra para que comprendieran el impacto del teatro. La encuesta reveló que la mayoría de los encuestados, tanto hombres como mujeres, opinaban que los hombres tienen más poder de control en la familia. También se descubrió que las decisiones se toman en su mayoría de forma conjunta en la familia. En cuanto al abuso físico como forma de violencia, la mayoría de los encuestados, principalmente las mujeres, respondieron afirmativamente y lo identificaron como una forma grave de violencia. Después de la representación teatral, se realizó un segundo nivel de encuesta con los mismos 50 encuestados y se reveló que el teatro era el medio preferido para generar conciencia entre las masas en comparación con otros medios. En este artículo también se presentan dos relatos de veinte estudios de caso para una comprensión más profunda. La justificación del estudio es que intenta establecer que el teatro es un medio de comunicación poderoso y aceptable para generar conciencia sobre la violencia contra las mujeres, particularmente en las áreas rurales y, por lo tanto, una herramienta eficaz para promover una sociedad con justicia de género.
