---
title: Desarrollo de capacidades para la reducción del riesgo de desastres en el entorno construido en América Latina y el Caribe (BERLAC)
author:
- name: América Bendito Shoichi Tabuchi y Soichiro Yasukawa
keywords:
- Entorno construido
- Códigos de construcción
- Resiliencia
- Terremoto
- Modernización
abstract: América Bendito^1\*,^ Shoichi Tabuchi^1^ y Soichiro Yasukawa^1^
categories:
- Sesión 20. Capacidad adaptativa y reducción de la vulnerabilidad ante riesgos ambientales y climáticos
---

América Bendito^1\*,^ Shoichi Tabuchi^1^ y Soichiro Yasukawa^1^

Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura (UNESCO), París, Francia

[[americabendito@gmail.com]{.underline}](mailto:americabendito@gmail.com)

América Latina y el Caribe (ALC) es la segunda región más propensa a desastres a nivel mundial, con 1.534 desastres que afectaron a 190 millones de personas desde el año 2000. Entre estos peligros, los terremotos han causado importantes víctimas y daños, agravados por la posición de la región dentro del \"Anillo de Fuego\" sísmico, que alberga más de una cuarta parte de los terremotos del mundo de magnitud 8,0 o superior, principalmente en América del Sur. En respuesta, la UNESCO implementó el proyecto de tres años titulado \"Desarrollo de capacidades para la reducción del riesgo de desastres en el entorno construido en América Latina y el Caribe\" (BERLAC) y financiado por el Gobierno japonés. El proyecto, estructurado en cuatro componentes, tuvo como objetivo fortalecer la seguridad del entorno construido en seis países de América Latina y el Caribe propensos a terremotos. A lo largo de la implementación de BERLAC, la UNESCO desarrolló directrices técnicas para el personal municipal destinadas a mejorar las inspecciones sistemáticas durante la construcción de viviendas, así como directrices para controlar la calidad de los materiales utilizados en el proceso. El segundo componente se centró en la seguridad de las instalaciones educativas, abordando diversos desafíos a través de soluciones innovadoras, incluida la tecnología de inteligencia artificial. El tercer componente propuso soluciones de modernización utilizando enfoques tradicionales e innovadores. Además, la UNESCO desarrolló recomendaciones de políticas basadas en el riesgo en el cuarto componente, centradas en todas las partes interesadas que participan en el proceso de construcción. Estas políticas podrían contribuir a una gobernanza más resiliente, adaptable y eficiente, permitiendo una planificación proactiva en lugar de reaccionar ante los desastres a medida que ocurren. Las políticas basadas en el riesgo son particularmente relevantes en un mundo dinámico, complejo e incierto que enfrenta diversos desafíos.
