---
title: 'Otro proyecto de la era temprana de la IA: visualización de áreas de refugio después de un desastre y exploración de necesidades y estándares con imágenes generadas por IA'
author:
- name: Sofia Kalogeromitrou
  affiliations:
  - Ingeniera arquitecta, Máster en Gestión Ambiental, de Crisis y Desastres, Atenas, Grecia
keywords:
- Desastre
- IA
- áreas de refugio
- visualización
abstract: '[[s.kalogeromitrou@gmail.com]{.underline}](mailto:s.kalogeromitrou@gmail.com)'
categories:
- Sesión 10. Inteligencia artificial, ciencia, tecnología e innovación
---

[[s.kalogeromitrou@gmail.com]{.underline}](mailto:s.kalogeromitrou@gmail.com)

En el ámbito de la gestión de desastres, el diseño y la funcionalidad de las áreas de refugio después de un desastre desempeñan un papel fundamental para garantizar la seguridad y el bienestar de las comunidades inmediatamente después de un evento catastrófico. Esta investigación explora un enfoque novedoso que aprovecha los generadores de imágenes de IA para producir representaciones visuales de estas áreas de refugio después de un terremoto. La literatura destaca una brecha en los estudios de recuperación posterior a una emergencia, en particular en el uso de tecnologías de visualización para abordar aspectos más amplios de la planificación de la recuperación y la simulación comunitaria (Zhu y Li, 2021). Esta exploración investiga si al adoptar la IA podríamos ser capaces de retratar la naturaleza dinámica de las áreas de refugio temporal después de un desastre. La metodología actual emplea un enfoque multifacético de generación de imágenes, comenzando con el uso de indicaciones verbales y luego con fotografías de espacios públicos al aire libre existentes que se designan como áreas de refugio después de un terremoto. Las imágenes generadas por IA podrían servir como prototipos de diseño para la usabilidad, la accesibilidad y la participación de la comunidad, lo que permitiría la exploración de diversas configuraciones espaciales, sistemas de señalización, diseños espaciales y la presencia dinámica de individuos dentro de estos espacios públicos. La incorporación de estrategias de visualización podría proporcionar una vía para futuras investigaciones, facilitando la exploración de las características espaciales y temporales de la recuperación de la infraestructura y la reconstrucción de la comunidad después de los desastres. En un contexto más amplio, la integración de la tecnología de IA en la visualización de áreas de refugio presenta una vía prometedora para la toma de decisiones informada, la formulación de políticas y la participación de la comunidad en la gestión de desastres, fomentando paisajes comunitarios más adaptables y receptivos.
