---
title: 'Mapas Comunitarios: una herramienta de participación en la Gestión de Riesgo de Desastres'
author:
- name: Evelin Langebeck Cuéllar
- name: Adriana M Rodríguez Ortiz
keywords:
- Comunidades
- Capacidades
- Percepción del riesgo
- Participación
- Mapas Comunitarios
abstract: Unidad Nacional de Gestión de Riesgo de Desastres, Bogotá, Colombia
categories:
- Sesión 17. Enfoques diferenciales de la GRD
---

Unidad Nacional de Gestión de Riesgo de Desastres, Bogotá, Colombia

[[evelin.langebeck@gmail.com]{.underline}](mailto:evelin.langebeck@gmail.com)

La participación comunitaria en gestión de riesgo de desastres es ampliamente discutida como un elemento necesario para alcanzar la gobernanza ante desastres, dando cumplimiento a las metas del Marco de Sendai, en los países de la región. En este sentido, se requieren herramientas y metodologías que abarquen procesos sociales alrededor de la GRD. Como respuesta, en Colombia la Ley 1523 de 2012, propone un principio participativo y de diversidad cultural, que incorpora a los actores y las diversidades en temas de organización y participación. De igual manera, en el artículo 18 de ésta misma Ley, se presentan los miembros de los Consejos Territoriales de Gestión de Riego de Desastres, entre ellos las organizaciones sociales y comunitarias. No obstante, en la práctica la participación de las comunidades no es representativa, tal como lo reporta el informe de seguimiento y evaluación de capacidades mínimas municipales en gestión de riesgo, en dónde en el numeral 9, promover la participación de las comunidades y el sector privado, se evidencia que municipios del país no hacen ningún reporte frente a este aspecto de la gestión del riesgo. En este marco, se propone fortalecer la participación de las comunidades, a través de una herramienta que permite la identificación y priorización de puntos relevantes, desde la percepción y memoria del riesgo, en los territorios, que dialogue con los instrumentos de planificación municipal en GRD, Es así como la metodología de mapas comunitarios se convierte en dicha herramienta que recoge el diagnóstico y brinda información sobre posibles lugares que se pueden afectar frente a una amenaza, así como la ubicación de las comunidades, la infraestructura y los bienes más vulnerables.
