---
title: El enfoque étnico diferencial como una estrategia para reducir el riesgo de desastres en Colombia
author:
- name: María del Mar Moreno Gómez
  affiliations:
  - Departamento de salud global, Karolinska Institutet, Estocolmo, Suecia.
- name: Erwin Hernández
  affiliations:
  - Departamento de Medicina Familiar y Salud Pública, Facultad de Medicina, Universidad de la Sabana, Chía, Colombia
- name: Camilo Correal
  affiliations:
  - Departamento de salud global, Karolinska Institutet, Estocolmo, Suecia.
keywords:
- Desastres; manejo del riesgo; Colombia; etnicidad; Diversidad cultural
abstract: '[[mariamorgo@unisabana.edu.co]{.underline}](mailto:mariamorgo@unisabana.edu.co)'
categories:
- Sesión 17. Enfoques diferenciales de la GRD
---

[[mariamorgo@unisabana.edu.co]{.underline}](mailto:mariamorgo@unisabana.edu.co)

Colombia es un país multicultural con una población donde aproximadamente el 13% corresponde a minorías étnicas, quienes tienen una mayor vulnerabilidad frente a los desastres. En respuesta a esta situación, se ha implementado el enfoque étnico diferencial como una estrategia clave en la reducción del riesgo de desastres. Este enfoque busca incorporar perspectivas étnicas en todos los procesos de gestión de riesgos para elevar el conocimiento comunitario y mejorar la comprensión de las dinámicas de riesgo. A pesar de los avances, la implementación de estas iniciativas enfrenta desafíos significativos, especialmente en la adopción de las directrices a nivel local, lo cual subraya la urgencia de fortalecer la integración de este enfoque en instituciones y comunidades locales. Además, es crucial fomentar el diálogo intercultural y la valoración del conocimiento científico-ancestral, integrando estas dimensiones en todas las fases del ciclo de gestión del riesgo de desastres. Este capítulo tiene como objetivo analizar la implementación y los retos del enfoque étnico diferencial en la gestión del riesgo de desastres en Colombia, destacando su importancia en la mitigación de la vulnerabilidad de estas comunidades ante desastres naturales. La incorporación efectiva de este enfoque no solo contribuye a la resiliencia local, sino que también promueve una gestión inclusiva y adaptada a las realidades culturales del país.
