---
title: 'Ocurrencia e impacto social de los desastres: caso de los deslizamientos en México'
author:
- name: Srahyrlandy Rocio Díaz Sánchez
  affiliations:
  - Departamento de Química, Universidad Autónoma del Estado de México, México
  corresponding: true
  email: sraydiaz@gmail.com
- name: Edel Cadena
  affiliations:
  - Departamento de Geografía, Universidad Autónoma del Estado de México, México
keywords:
- Deslizamientos
- Inventario
- Riesgo
- Historicidad
- Población
abstract: Es común escuchar la frase "quien no conoce su historia está condenado a repetirla". En efecto, conocer la historicidad de los eventos naturales es fundamental no sólo para datarlos sino también
  para determinar sus causas y efectos. Es un primer paso en la estimación de la recurrencia, es decir, la posibilidad de que los eventos vuelvan a ocurrir en condiciones similares, así como en la localización
  de zonas con alto riesgo de desastre. Las Naciones Unidas (ONU 2005) identifican el desarrollo y la mejora de bases de datos pertinentes como una prioridad clave para el desarrollo de capacidades de los
  países en desarrollo (Taylor et al. 2015).
categories:
- Sesión 5. Modelado y pronóstico de geoamenazas
---

Es común escuchar la frase "quien no conoce su historia está condenado a repetirla". En efecto, conocer la historicidad de los eventos naturales es fundamental no sólo para datarlos sino también para determinar sus causas y efectos. Es un primer paso en la estimación de la recurrencia, es decir, la posibilidad de que los eventos vuelvan a ocurrir en condiciones similares, así como en la localización de zonas con alto riesgo de desastre. Las Naciones Unidas (ONU 2005) identifican el desarrollo y la mejora de bases de datos pertinentes como una prioridad clave para el desarrollo de capacidades de los países en desarrollo (Taylor et al. 2015).

Los inventarios de deslizamientos son de suma importancia, ya que son vitales para el análisis de amenazas. En este estudio se presenta una metodología para estimar el impacto social de los desastres con énfasis en los deslizamientos en México. Si bien existen estudios de monitoreo de deslizamientos en zonas específicas del país, hasta el momento no se ha publicado un catálogo histórico que sirva de base para el análisis espacio-temporal y la determinación del impacto en términos de pérdidas de vidas humanas. Los eventos reportados se categorizaron en los siguientes tipos de desplazamientos: caída, deslizamiento y movimiento complejo y flujo; los datos se estandarizaron y almacenaron mediante el software SPSS. Además, se realizaron estimaciones para conocer el número de personas que pudieron haber sido afectadas por deslizamientos en 2019 con base en su relación con los niveles de marginación a nivel nacional, elaborados por el Consejo Nacional de Población (CONAPO). Los grados de marginación representan la exclusión de una población del desarrollo a través de desigualdades socioeconómicas que se manifiestan en bajos ingresos y en la falta de educación, salud, infraestructura y acceso a servicios básicos. Se encontró que las localidades con niveles de marginación alta y muy alta concentran casi la mitad de los deslizamientos ocurridos en 82 años. Este estudio revela nuevos hallazgos en cuanto a la distribución espacial de los eventos y las poblaciones afectadas que se consideran una valiosa aportación al estudio de los deslizamientos en México.
