---
title: Alta Gerencia para la Gestión del Riesgo
author:
- name: Ciro Ugarte
  affiliations:
  - Organización Panamericana de la Salud (OPS), Director del Departamento de Emergencias de Salud
- name: Gina Tambini
  affiliations:
  - Organización Panamericana de la Salud (OPS), Representante en Colombia para la Organizacion Panamericana de la Salud / Organizacion Mundial de la Salud.
- name: Mauricio Cerpa Calderón
  affiliations:
  - Organización Panamericana de la Salud (OPS), Asesor internacional de emergencias en salud para Colombia
keywords:
- resiliencia
- salud
- respuesta sanitaria
- prevención
abstract: Se destacó la importancia de fortalecer la resiliencia de los sistemas de salud en las Américas a través de la sesión \"Emergencias y Salud\". Se compartieron conocimientos, experiencias exitosas
  y lecciones aprendidas en la prevención, reducción de riesgos, preparación, vigilancia, respuesta y recuperación temprana ante amenazas para la salud humana. Además, se enfatizó la necesidad de gestionar
  los riesgos y promover la reducción de desastres mediante una cultura de prevención y desarrollo sostenible, con el fin de mejorar la capacidad de respuesta de los sistemas de salud. El Departamento de
  Emergencias de Salud de la OPS brindó su apoyo experto a los países miembros para enfrentar emergencias y desastres de origen natural, biológico, químico, radiológico o humano. La sesión contó con la
  participación de personal de OPS/OMS y representantes de los Ministerios de Salud de varios países de la región, quienes intercambiaron ideas y estrategias para fortalecer la capacidad regional en la
  respuesta a crisis sanitarias. Esta colaboración fue clave para avanzar hacia sistemas de salud más seguros y sostenibles en toda la región.
categories:
- Sesiones Especiales
---

**Sobre la sesión:** Se destacó la importancia de fortalecer la resiliencia de los sistemas de salud en las Américas a través de la sesión \"Emergencias y Salud\". Se compartieron conocimientos, experiencias exitosas y lecciones aprendidas en la prevención, reducción de riesgos, preparación, vigilancia, respuesta y recuperación temprana ante amenazas para la salud humana. Además, se enfatizó la necesidad de gestionar los riesgos y promover la reducción de desastres mediante una cultura de prevención y desarrollo sostenible, con el fin de mejorar la capacidad de respuesta de los sistemas de salud. El Departamento de Emergencias de Salud de la OPS brindó su apoyo experto a los países miembros para enfrentar emergencias y desastres de origen natural, biológico, químico, radiológico o humano. La sesión contó con la participación de personal de OPS/OMS y representantes de los Ministerios de Salud de varios países de la región, quienes intercambiaron ideas y estrategias para fortalecer la capacidad regional en la respuesta a crisis sanitarias. Esta colaboración fue clave para avanzar hacia sistemas de salud más seguros y sostenibles en toda la región.

**Objetivos:** 1) Comprender el riesgo de desastres desde una perspectiva gerencial en el sector salud. 2) Fortalecer la gobernanza del riesgo de desastres para una gestión eficaz en sistemas de salud. 3) Invertir en la reducción del riesgo de desastres para la resiliencia de los servicios de salud desde una perspectiva de desarrollo. 4) Mejorar la preparación ante desastres para una respuesta eficaz y una \"reconstrucción mejor\" en materia de recuperación, rehabilitación y reconstrucción sostenibles en el sector salud.

**Justificación**: Se subrayó la urgencia y complejidad de los desafíos en la gestión del riesgo de desastres en salud, destacando la relevancia del Marco de Sendai 2015-2030 y su llamado a la acción conjunta entre gobiernos, organismos internacionales, ONG y sector privado. En este marco, se analizó la iniciativa "Hospital Resiliente" de la OPS/OMS como estrategia clave para asegurar la operatividad de los servicios de salud ante desastres. Se compartieron experiencias de implementación en distintos países, evidenciando su impacto en la reducción de vulnerabilidades. La pandemia de COVID-19 evidenció la necesidad de fortalecer la preparación y respuesta ante emergencias, resaltando el rol de la OMS en la coordinación global y en el robustecimiento de la arquitectura para la respuesta sanitaria (HEPR). En Colombia, se discutió la incorporación de hospitales resilientes en el Plan Nacional de Desarrollo 2022-2026 y su articulación con el Plan Decenal de Salud Pública 2022-2031, reafirmando el compromiso con servicios de salud resilientes y equitativos. También se enfatizó el papel del talento humano, alineado con el Eje Estratégico 6 del Plan Decenal. La sesión abordó los desafíos de grupos históricamente marginados ---mujeres, personas con movilidad reducida, comunidad LGBTIQ+ y grupos étnicos---, insistiendo en estrategias inclusivas y equitativas. La OPS promovió el intercambio de experiencias entre países, fortaleciendo la cooperación internacional y el aprendizaje mutuo. En conclusión, se reafirmó la necesidad de integrar las voces comunitarias en todas las fases de la gestión del riesgo, impulsando una resiliencia inclusiva y sostenible.
