---
title: 'Comprendiendo los efectos del cambio climático en el Reino Unido: perspectivas extraídas de las encuestas de percepción pública'
author:
- name: Mark Ashley Parry
  affiliations:
  - Universidad de Northumbria, Newcastle-upon-Tyne, Reino Unido
  corresponding: true
  email: ashley2.parry@northumbria.ac.uk
keywords:
- Cambio climático
- Educación
- Reino Unido
abstract: En los últimos años, el Reino Unido ha observado una serie de fenómenos meteorológicos extremos, que algunos atribuyen al impacto del cambio climático. Este artículo explora las percepciones de
  los impactos del cambio climático en el Reino Unido, utilizando una investigación pragmática que integra una combinación de métodos para captar una comprensión integral de este problema multidisciplinario
  (socioambiental). Un componente principal de la investigación implicó un cuestionario detallado realizado entre marzo y septiembre de 2017, utilizando preguntas abiertas y cerradas para extraer las opiniones
  de la sociedad civil sobre el cambio climático, incluidos los impactos. Además, se utilizaron datos de las encuestas del Departamento de Negocios, Energía y Estrategia Industrial (BEIS) de marzo de 2019
  y marzo de 2020 para crear una instantánea anual para buscar tendencias.
categories:
- Sesión 4. Percepción del riesgo, comportamiento humano y cultura
---

En los últimos años, el Reino Unido ha observado una serie de fenómenos meteorológicos extremos, que algunos atribuyen al impacto del cambio climático. Este artículo explora las percepciones de los impactos del cambio climático en el Reino Unido, utilizando una investigación pragmática que integra una combinación de métodos para captar una comprensión integral de este problema multidisciplinario (socioambiental). Un componente principal de la investigación implicó un cuestionario detallado realizado entre marzo y septiembre de 2017, utilizando preguntas abiertas y cerradas para extraer las opiniones de la sociedad civil sobre el cambio climático, incluidos los impactos. Además, se utilizaron datos de las encuestas del Departamento de Negocios, Energía y Estrategia Industrial (BEIS) de marzo de 2019 y marzo de 2020 para crear una instantánea anual para buscar tendencias.

Los hallazgos revelan una percepción significativa entre el público británico de que el cambio climático ya está afectando al Reino Unido, con un mayor reconocimiento de los fenómenos meteorológicos extremos, como las olas de calor y las inundaciones. Sin embargo, los datos indican que existe una conciencia general y creciente de los riesgos inmediatos y futuros que plantea el cambio climático. Además, el estudio destaca que la percepción pública está significativamente influenciada por eventos vividos recientemente, como fenómenos meteorológicos extremos. Eventos como la ola de calor de febrero de 2019 y las graves inundaciones invernales de principios de 2020 sirvieron para aumentar la conciencia pública sobre los impactos del cambio climático, pero juegan un papel en la percepción de los riesgos del cambio climático. Sin embargo, existen variaciones notables en la percepción entre los diferentes grupos de edad, y los individuos más jóvenes tienen menos probabilidades de reconocer ciertos impactos en comparación con las generaciones mayores.

Por lo tanto, este estudio subraya la importancia de abordar la conciencia pública y desarrollar estrategias adaptativas para mitigar y adaptarse a los efectos adversos del cambio climático.
